stages:
  - build
  #- test
  - archive

build-linux:
  stage: build
  tags:
    - ubuntu-23
  script:
    - echo "Starting Linux build..."
    # the VM creates an X authority at /home/gitlab/.Xauthority at login.
    # the VM machine needs to copy this file to /home/gitlab-runner/.Xauthority at boot (lightdm start)
    # to allow us to get an X connection (used by GLFW) otherwise: "/usr/bin/ld: cannot find -lXxf86vm"
    - export DISPLAY=:0
    - mkdir gitlab-build
    - cd gitlab-build
    - /usr/bin/cmake
      -G"Ninja"
      -DCMAKE_C_COMPILER=/usr/bin/clang
      -DCMAKE_CXX_COMPILER=/usr/bin/clang++
      -DAE_BUILD_ASSIMP=ON
      -DAE_BUILD_BULLET=ON
      -DAE_BUILD_GLFW=ON
      -DGITLAB_CI_PIPELINE_CREATED_AT="${CI_PIPELINE_CREATED_AT}"
      -DGITLAB_CI_PIPELINE_IID="${CI_PIPELINE_IID}"
      ..
    - /usr/bin/cmake --build . -j4
    - echo "Linux build complete."

build-macos:
  stage: build
  tags:
    - macos-12.6
  script:
    - echo "Starting macOS build..."
    - mkdir gitlab-build
    - cd gitlab-build
    - /opt/local/bin/cmake
      -G"Ninja"
      -DAE_BUILD_ASSIMP=ON
      -DAE_BUILD_BULLET=ON
      -DAE_BUILD_GLFW=ON
      -DGITLAB_CI_PIPELINE_CREATED_AT="${CI_PIPELINE_CREATED_AT}"
      -DGITLAB_CI_PIPELINE_IID="${CI_PIPELINE_IID}"
      ..
    - /opt/local/bin/cmake --build . -j4
    - echo "macOS build complete."

build-windows:
  stage: build
  tags:
    - windows-10
  script:
    - echo "Starting Windows build..."
    - tar --version
    - mkdir gitlab-build
    - cd gitlab-build
    - cmake
      -T"ClangCL"
      -DCMAKE_TOOLCHAIN_FILE="C:/Program Files/vcpkg/scripts/buildsystems/vcpkg.cmake"
      -DAE_BUILD_ASSIMP=ON
      -DAE_BUILD_BULLET=ON
      -DAE_BUILD_GLFW=ON
      -DGITLAB_CI_PIPELINE_CREATED_AT="${CI_PIPELINE_CREATED_AT}"
      -DGITLAB_CI_PIPELINE_IID="${CI_PIPELINE_IID}"
      ..
    - cmake --build . -j8
    - echo "Windows build complete."

# test-linux:
#   stage: test
#   tags:
#       - debian-11
#   script:
#     - echo "Starting Linux test..."

# test-macos:
#   stage: test
#   tags:
#       - macos-12.6
#   script:
#     - echo "Starting macOS test..."

# test-windows:
#   stage: test
#   tags:
#       - windows-10
#   script:
#     - echo "Starting Windows test..."

archive-debug-linux:
  # TODO: 1. 'testing' only
  # TODO: 2. get build type? debug? release?
  stage: archive
  #only:
  #  - testing (#1)
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "testing"'
  environment: production
  tags:
    - ubuntu-23
  script:
    - echo "Starting Linux debug archive..."
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - packaged/debug
    expire_in: 1 week

archive-debug-macos:
  stage: archive
  only:
    - testing
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "testing"'
  environment: production
  tags:
    - macos-12.6
  script:
    - echo "Starting macOS debug archive..."

archive-debug-windows:
  stage: archive
  only: 
    - testing
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "testing"'
  environment: production
  tags:
    - windows-10
  script:
    - echo "Starting Windows debug archive..."

archive-release-linux:
  stage: archive
  only:
    - master
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  environment: production
  tags:
    - debian-11
  script:
    - echo "Starting Linux release archive..."

archive-release-macos:
  stage: archive
  only:
    - master
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  environment: production
  tags:
    - macos-12.6
  script:
    - echo "Starting macOS release archive..."

archive-release-windows:
  stage: archive
  only:
    - master
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  environment: production
  tags:
    - windows-10
  script:
    - echo "Starting Windows release archive..."
