
SET(UBUNTU_CROSS True)

SET(CMAKE_SYSTEM_NAME Darwin)

SET(CMAKE_C_COMPILER x86_64-apple-darwin15-clang)
SET(CMAKE_CXX_COMPILER x86_64-apple-darwin15-clang++)

SET(CMAKE_FIND_ROOT_PATH /opt/osxcross/target/macports/pkgs/opt/local/)
SET(CMAKE_OSX_SYSROOT /opt/osxcross/target/SDK/MacOSX10.11.sdk/)

SET(CMAKE_INSTALL_FRAMEWORK_PREFIX "/opt/osxcross/target/SDK/MacOSX10.11.sdk/System/Library/Frameworks")

#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
