if (NOT DEFINED SOURCE_DIRECTORY OR SOURCE_DIRECTORY STREQUAL "")
	message(FATAL_ERROR "SOURCE_DIRECTORY is required.")
endif ()

if (NOT DEFINED DESTINATION_DIRECTORY OR DESTINATION_DIRECTORY STREQUAL "")
	message(FATAL_ERROR "DESTINATION_DIRECTORY is required.")
endif ()

if (NOT IS_DIRECTORY "${SOURCE_DIRECTORY}")
	message(FATAL_ERROR
			"Source directory does not exist: ${SOURCE_DIRECTORY}")
endif ()

file(MAKE_DIRECTORY "${DESTINATION_DIRECTORY}")

file(COPY "${SOURCE_DIRECTORY}/"
		DESTINATION "${DESTINATION_DIRECTORY}"
		USE_SOURCE_PERMISSIONS)
