//
//  Wedge.cc
//  avara3d
//
//  Created by Morgan Davis on 3/21/26.
//  Copyright © 2026 Morgan K Davis. All rights reserved.
//

#include "a3d/mesh/primitive/Wedge.h"

#include <generator/generator.hpp>

#include "a3d/mesh/Mesh.h"
#include "a3d/mesh/MeshElement.h"
#include "a3d/mesh/PrimitiveTopology.h"
#include "a3d/mesh/VertexFormats.h"
#include "a3d/visual/material/Material.h"

using namespace a3d::math;
using namespace std;

namespace a3d {

// [Pubic Static Members]

shared_ptr<Mesh> Wedge::Mesh(float                      length,
                             float                      width,
                             float                      height,
                             unsigned                   lengthSegments,
                             unsigned                   widthSegments,
                             unsigned                   heightSegments,
                             const shared_ptr<Material> material) {

    return make_shared<a3d::Mesh>("Wedge",
                                  make_unique<Wedge>(length, width, height, lengthSegments, widthSegments,
                                                     heightSegments),
                                  material);
}

// [Public Lifecycle Functions]

Wedge::Wedge(float    length,
             float    width,
             float    height,
             unsigned runSegments,
             unsigned widthSegments,
             unsigned riseSegments):
    MeshElement {},
    _length {length},
    _width {width},
    _height {height},
    _runSegments {math::max(1u, runSegments)},
    _widthSegments {math::max(1u, widthSegments)},
    _riseSegments {math::max(1u, riseSegments)} {

    // generated by ChatGPT

    using namespace a3d::math;

    const float L = _length;
    const float W = _width;
    const float H = _height;

    const float x0 = -L * 0.5f;  // pointy side
    const float x1 = L * 0.5f;  // thick/tall side
    const float z0 = -W * 0.5f;
    const float z1 = W * 0.5f;

    const unsigned nRun = _runSegments;
    const unsigned nWidth = _widthSegments;
    const unsigned nRise = _riseSegments;

    // Bottom + slope + thick face
    const uint32_t faceVerts = (nRun + 1) * (nWidth + 1) +  // bottom
                               (nRun + 1) * (nWidth + 1) +  // slope
                               (nRise + 1) * (nWidth + 1);  // thick face

    const uint32_t faceTris = 2 * nRun * nWidth +    // bottom
                              2 * nRun * nWidth +    // slope
                              2 * nRise * nWidth;   // thick face

    // Each cap:
    // row 0 = 1 vertex (tip)
    // rows 1..nRun = (nRise + 1) vertices each
    const uint32_t capVertsPerCap = 1 + nRun * (nRise + 1);
    const uint32_t capTrisPerCap = nRise * (2 * nRun - 1);

    const uint32_t reserveVerts = faceVerts + 2 * capVertsPerCap;
    const uint32_t reserveTris = faceTris + 2 * capTrisPerCap;

    beginBuild(VertexLayout::PNT, static_cast<uint16_t>(sizeof(VertexPNT)), PrimitiveTopology::Triangles,
               IndexFormat::U32, reserveVerts, reserveTris * 3);

    auto addVertex = [&](const vec3& p, const vec3& n, const vec2& uv) -> uint32_t {
        const uint32_t  idx = _vertexCount;
        const VertexPNT v {p, n, uv};
        appendVertexBytes(&v);
        return idx;
    };

    auto addGridFace = [&](const vec3& origin, const vec3& uDir, const vec3& vDir, const vec3& normal,
                           unsigned uSegs, unsigned vSegs) {
        std::vector<uint32_t> verts;
        verts.reserve((uSegs + 1) * (vSegs + 1));

        for (unsigned iu = 0; iu <= uSegs; ++iu) {
            const float u = static_cast<float>(iu) / static_cast<float>(uSegs);

            for (unsigned iv = 0; iv <= vSegs; ++iv) {
                const float v = static_cast<float>(iv) / static_cast<float>(vSegs);
                const vec3  p = origin + uDir * u + vDir * v;
                verts.push_back(addVertex(p, normal, vec2(u, v)));
            }
        }

        const bool reverse = dot(cross(uDir, vDir), normal) < 0.0f;

        for (unsigned iu = 0; iu < uSegs; ++iu) {
            for (unsigned iv = 0; iv < vSegs; ++iv) {
                const uint32_t a = verts[iu * (vSegs + 1) + iv];
                const uint32_t b = verts[(iu + 1) * (vSegs + 1) + iv];
                const uint32_t c = verts[(iu + 1) * (vSegs + 1) + (iv + 1)];
                const uint32_t d = verts[iu * (vSegs + 1) + (iv + 1)];

                if (!reverse) {
                    appendTriangle(a, b, c);
                    appendTriangle(a, c, d);
                }
                else {
                    appendTriangle(a, c, b);
                    appendTriangle(a, d, c);
                }
            }
        }
    };

    auto addTriCap = [&](float z, const vec3& normal) {
        const bool reverse = normal.z < 0.0f;

        std::vector<std::vector<uint32_t>> rows;
        rows.resize(nRun + 1);

        // Row 0: just the tip.
        rows[0].push_back(addVertex(vec3(x0, 0.0f, z), normal, vec2(0.0f, 0.0f)));

        // Rows 1..nRun: vertical samples from bottom edge to slope edge.
        for (unsigned i = 1; i <= nRun; ++i) {
            const float u = static_cast<float>(i) / static_cast<float>(nRun);
            const float x = x0 + (x1 - x0) * u;
            const float maxY = H * u;

            rows[i].reserve(nRise + 1);

            for (unsigned j = 0; j <= nRise; ++j) {
                const float v = static_cast<float>(j) / static_cast<float>(nRise);
                const float y = maxY * v;

                rows[i].push_back(addVertex(vec3(x, y, z), normal, vec2(u, v)));
            }
        }

        // Fan between tip row and first full row.
        for (unsigned j = 0; j < nRise; ++j) {
            const uint32_t a = rows[0][0];
            const uint32_t b = rows[1][j];
            const uint32_t c = rows[1][j + 1];

            if (!reverse) {
                appendTriangle(a, b, c);
            }
            else {
                appendTriangle(a, c, b);
            }
        }

        // Quad strips between subsequent rows.
        for (unsigned i = 1; i < nRun; ++i) {
            for (unsigned j = 0; j < nRise; ++j) {
                const uint32_t a = rows[i][j];
                const uint32_t b = rows[i + 1][j];
                const uint32_t c = rows[i + 1][j + 1];
                const uint32_t d = rows[i][j + 1];

                if (!reverse) {
                    appendTriangle(a, b, c);
                    appendTriangle(a, c, d);
                }
                else {
                    appendTriangle(a, c, b);
                    appendTriangle(a, d, c);
                }
            }
        }
    };

    //
    // Bottom face
    //
    addGridFace(vec3(x0, 0.0f, z0), vec3(L, 0.0f, 0.0f),   // run
                vec3(0.0f, 0.0f, W),   // width
                vec3(0.0f, -1.0f, 0.0f), nRun, nWidth);

    //
    // Sloped face
    //
    addGridFace(vec3(x0, 0.0f, z0), vec3(L, H, 0.0f),      // run + rise
                vec3(0.0f, 0.0f, W),   // width
                normalize(vec3(-H, L, 0.0f)), nRun, nWidth);

    //
    // Thick vertical face at +X
    //
    addGridFace(vec3(x1, 0.0f, z0), vec3(0.0f, H, 0.0f),   // rise
                vec3(0.0f, 0.0f, W),   // width
                vec3(1.0f, 0.0f, 0.0f), nRise, nWidth);

    //
    // Left cap (z = z0), outward = -Z
    //
    addTriCap(z0, vec3(0.0f, 0.0f, -1.0f));

    //
    // Right cap (z = z1), outward = +Z
    //
    addTriCap(z1, vec3(0.0f, 0.0f, 1.0f));

    endBuild(true);
}

// workd, but not capped.
//Wedge::Wedge(float length,
//		 float width,
//		 float height,
//		 unsigned lengthSegments,
//		 unsigned widthSegments,
//		 unsigned heightSegments):
//		MeshElement{},
//		_length{length},
//		_width{width},
//		_height{height},
//		_lengthSegments{lengthSegments},
//		_widthSegments{widthSegments},
//		_heightSegments{heightSegments} {
//
//	using namespace generator;
//
//	auto e0 = LineShape({-length * 0.5, 0.0}, {+length * 0.5, 0.0}, lengthSegments);
//	auto e1 = LineShape({+length * 0.5, 0.0}, {+length * 0.5, height},   heightSegments);
//	auto e2 = LineShape({+length * 0.5, height},   {-length * 0.5, 0.0}, lengthSegments);
//
//	auto triProfile = MergeShape<LineShape, LineShape, LineShape>(e0, e1, e2);
//
//	auto path = LinePath(
//			{0.0, 0.0, -width * 0.5},
//			{0.0, 0.0, +width * 0.5},
//			{1.0, 0.0, 0.0},
//			widthSegments );
//
//	auto wedge = extrudeMesh(triProfile, path);
//
//	beginBuild(VertexLayout::PNT,
//			   (uint16_t)sizeof(VertexPNT),
//			   PrimitiveTopology::Triangles,
//			   IndexFormat::U16);
//
//	// --- vertices ---
//	for (auto vs = wedge.vertices(); !vs.done(); vs.next()) {
//		const auto v = vs.generate();
//		const VertexPNT out{
//				{ (float)v.position[0], (float)v.position[1], (float)v.position[2] },
//				{ (float)v.normal[0],   (float)v.normal[1],   (float)v.normal[2]   },
//				{ (float)v.texCoord[0], (float)v.texCoord[1] } };
//		appendVertexBytes(&out);
//	}
//
//	// --- triangles (collect, reverse order like your old _faces reverse) ---
//	std::vector<std::array<uint32_t, 3>> tris;
//	for (auto ts = wedge.triangles(); !ts.done(); ts.next()) {
//		const auto t = ts.generate();
//		tris.push_back({ (uint32_t)t.vertices[0],
//						 (uint32_t)t.vertices[1],
//						 (uint32_t)t.vertices[2] });
//	}
//
//	//std::reverse(tris.begin(), tris.end());
//
//	for (const auto& tri : tris) {
//		appendTriangle(tri[0], tri[1], tri[2]);
//	}
//
//	endBuild(true);
//}

// [Public Member Functions]

float Wedge::length() const {
    return _length;
}

float Wedge::width() const {
    return _width;
}

float Wedge::height() const {
    return _height;
}

unsigned Wedge::runSegments() const {
    return _runSegments;
}

unsigned Wedge::widthSegments() const {
    return _widthSegments;
}

unsigned Wedge::riseSegments() const {
    return _riseSegments;
}

} // namespace a3d
