//
//  App.h
//  030-rigidbody
//
//  Created by Morgan Davis on 7/17/26.
//  Copyright © 2026 Morgan K Davis. All rights reserved.
//

#ifndef AVARA3D_TEST_RIGIDBODY_APP_H
#define AVARA3D_TEST_RIGIDBODY_APP_H

#include <memory>
#include <vector>

#include "a3d/Application.h"
#include "a3d/Math.h"

namespace a3d {
	struct HostUpdateInfo;
	struct RenderFrameInfo;
	class Mesh;
	class Node;
	class PhysicsShape;
	class PhysicsWorld;
	class Runner;
	class Scene;
	class VisualWorld;
	class Window;
}

namespace a3d::ext {
	struct WanderRotator;
}

namespace test::rigidbody {

	class App : public a3d::Application {

	public:
		/// Public Lifecycle Functions ///

		App(int argc, char* argv[]);
		~App() override;

		App(const App&) = delete;
		App& operator=(const App&) = delete;

		App(App&&) = delete;
		App& operator=(App&&) = delete;

		/// Internal Types ///

		using DuckFruitDef = std::tuple<
			std::shared_ptr<a3d::Mesh>,
			std::shared_ptr<a3d::PhysicsShape>,
			float>;

	protected:
		/// Protected Member Functions ///

		std::unique_ptr<a3d::Scene> init() override;
		a3d::SimulationConfiguration simulationConfiguration() const override;

		bool shouldContinue(const a3d::Scene& scene) override;

		void didShutdown() override;

		/// Runner Callback Overrides ///

		void runnerUpdate(a3d::Runner& runner,
		                  const a3d::HostUpdateInfo& info) override;

		/// Scene Callback Overrides ///

		void sceneWillSimulate(a3d::Scene& scene,
		                       const a3d::SimulationStepInfo& info) override;

		/// VisualWorld Callback Overrides ///

		void visualWorldDidRender(a3d::VisualWorld& world,
		                          const a3d::RenderFrameInfo& info) override;

		void visualWorldWillRender(a3d::VisualWorld& world,
		                           const a3d::RenderFrameInfo& info) override;

	private:
		/// Private Types ///

		enum class Command {
			DuckBoundingBox,
			DuckConvexHull,
			DuckConcavePolyhedron,
			DuckMassZero,
			DuckMassTen,
			DuckMassOneHundred,
			RemoveCylinderBodies,
			RemoveDynamicBodies,
			AddBoxes,
			SpawnAutogeneratedPrimitives,
			SpawnChainMail,
			SpawnRecursiveTestTree,
			SpawnHacdTeapot,
			AddRing
		};

		/// Private Member Variables ///

		std::unique_ptr<a3d::Window>				_window;
		a3d::Node*									_duckNode;
		std::vector<DuckFruitDef>					_duckFruit;
		std::vector<Command>						_pendingCommands;
		std::unique_ptr<a3d::ext::WanderRotator>	_duckRotator;
		float										_cameraMoveSpeed;
		bool										_spawnDuckFruit;
		bool										_spawnDuckFruitPending;
		double										_duckFruitSpawnAccumulator;
		bool										_shootSlurm;
		bool										_shootSlurmPending;
		double										_slurmShotAccumulator;
		a3d::math::vec3								_slurmLocation;
		a3d::math::vec3								_slurmDirection;
	};
}

#endif // AVARA3D_TEST_RIGIDBODY_APP_H
