//
//  App.cc
//  030-rigidbody
//
//  Created by Morgan Davis on 7/17/26.
//  Copyright © 2026 Morgan K Davis. All rights reserved.
//

#include "App.h"

#include <algorithm>
#include <chrono>
#include <memory>
#include <string>
#include <thread>
#include <tuple>
#include <utility>
#include <vector>

#include "a3d/a3d.h"
#include "a3d/mesh/ConvexDecomposer.h" // temporary

using namespace a3d;
using namespace a3d::math;
using namespace std;
using namespace test::rigidbody;

/// Private Constants ///

const Log::Level                      APP_LOG_LEVEL {Log::Level::Debug};
const uvec2                           WINDOW_SIZE {1280, 768};
const bool                            FULLSCREEN {false};
const bool                            ENABLE_HIGH_DPI {true};
const RenderContext::AntialiasingMode AA_MODE {RenderContext::AntialiasingMode::Msaa16X};
const bool                            ENABLE_VSYNC {false};
const bool                            USE_DEFAULT_LIGHTING {false};
const bool                            CAPTURE_CURSOR {false};
#if defined(A3D_WEB)
const float TIMESTEP {1.0 / 30.0};
#else
const float TIMESTEP {1.0 / 120.0};
#endif
const chrono::milliseconds DUCK_FRUIT_SPAWN_INTERVAL {100};
const chrono::milliseconds SLURM_SHOT_INTERVAL {50};

/// Private Static Non-Member Prototypes ///

void             SpawnDuckFruit(Scene& scene, const Node& duckNode, vector<App::DuckFruitDef>& duckFruit);
void             ShootSlurm(Scene& scene, const vec3& location, const vec3& direction);
void             AddCardboardBox(Scene& scene, const vec3& location, const vec3& axis, float angle);
void             SpawnHACDTeapot(Scene& scene);
void             AddBoxes(Scene& scene);
void             AddCardboardBoxes(Scene& scene);
void             AddRing(Scene& scene);
shared_ptr<Node> ColoredSphereNode(shared_ptr<Color> color, string name);
void             SpawnRecursiveTestTree(Scene& scene);
void             SpawnAutogeneratedPrimitives(Scene& scene);
void             SpawnInvisiblePrimitives(Scene& scene);
shared_ptr<Node> ChainmailLink(float minorRadius, float majorRadius);
void             SpawnChainMail(Scene& scene);

/// Public Lifecycle Functions ///

App::App(int argc, char* argv[]):
    Application(argc, argv, APP_LOG_LEVEL),
    _duckNode {nullptr},
    _duckFruitTrigger {DUCK_FRUIT_SPAWN_INTERVAL},
    _slurmTrigger {SLURM_SHOT_INTERVAL} {}

App::~App() = default;

/// Application Protected Member Functions ///

unique_ptr<Scene> App::init() {
    try {
        _window = make_unique<Window>(RenderContext::RenderingApi::OpenGL, *util::fs::ExecutableName(),
                                      WINDOW_SIZE, FULLSCREEN, ENABLE_HIGH_DPI, AA_MODE);
        _window->vSyncEnabled(ENABLE_VSYNC);
        _window->cursorCaptured(CAPTURE_CURSOR);

        auto visualWorld = make_unique<VisualWorld>(*_window);
        visualWorld->fog(Fog {
            .color = Color::DarkGray(),
            .startDistance = 50.0f,
            .endDistance = 400.0f,
            .transitionExponent = 1.0f,
        });
        Material::Property background = Color::Black();
        // auto background = make_shared<Texture>(util::filesystem::CubeImageNamed("stormy", "png"));
        visualWorld->background(Background {Color::Black()});

        auto physicsWorld = make_unique<PhysicsWorld>();

        auto scene =
            make_unique<Scene>(std::move(visualWorld), std::move(physicsWorld), Window::InputContext());
        scene->debugOptions(Scene::DebugOptions::ShowStatsOverlay);
        //scene->visualWorld()->usesDefaultLighting(true);

        // ambient light

        auto ambientColor = make_shared<Color>(.25f);
        auto ambientLight = make_shared<AmbientLight>(ambientColor);
        auto ambientLightNode = Node::LightNode(ambientLight);
        scene->rootNode()->addChild(ambientLightNode);

        // directional light

        auto sunColor = Color::LightGray();
        auto sunLight = make_shared<DirectionalLight>(sunColor);
        auto sunNode = Node::LightNode(sunLight);
        sunNode->eulerAngles({radians(0.0f), radians(45.0), radians(0.0)});
        scene->rootNode()->addChild(sunNode);

        static const float PLANE_LENGTH = 50.0;
        static const float PLANE_WIDTH = 50.0;
        auto               planeNode = Node::NamedNode("Ground plane node");
        planeNode->mesh(Box::Mesh(PLANE_LENGTH, .1f, PLANE_WIDTH));

        shared_ptr<Material> planeMaterial =
            make_shared<Material>(monostate {}, Color::DarkGray(), Color::LightGray());
        planeMaterial->locksAmbientWithDiffuse(false);
        planeMaterial->uvScale(PLANE_LENGTH / 10.0);
        planeMaterial->doubleSided(false);
        planeNode->mesh()->addMaterial(planeMaterial);
        planeNode->position({planeNode->position().x, 0, planeNode->position().z});

        auto planePhysicsBody = PhysicsBody::StaticBody();
        planePhysicsBody->friction(1);
        planePhysicsBody->restitution(0.25);
        planeNode->physicsBody(std::move(planePhysicsBody));

        scene->rootNode()->addChild(planeNode);

        // add the palm tree

        auto palmNode = Node::MeshNode(util::fs::MeshNamed("cartoon_palm_tree/cartoon_palm_tree"));
        palmNode->name("Palm tree");
        auto palmPhysicsBody = PhysicsBody::StaticBody();
        //palmPhysicsBody->mass(0);
        palmPhysicsBody->friction(1);
        palmPhysicsBody->restitution(0.25);
        palmNode->physicsBody(std::move(palmPhysicsBody));
        scene->rootNode()->addChild(palmNode);

        // add the duck

        auto duckNode = Node::MeshNode(util::fs::MeshNamed("rubber_duck/rubber_duck"));
        duckNode->name("Quack");
        _duckNode = duckNode.get();
        duckNode->position({/*4.5*/ 0, 25, 0});

        //	// #0
        //	_duckNode->physicsBody(PhysicsBody::KinematicBody());
        //	_duckNode->physicsBody()->shape()->type(PhysicsShape::Type::ConcavePolyhedron);
        ////	_duckNode->physicsBody()->shape()->type(PhysicsShape::Type::ConvexHull);
        //
        //	// #1
        ////	_duckNode->physicsBody(PhysicsBody::KinematicBody());
        ////	auto duckPhysicsShape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, _duckNode.get());
        ////	_duckNode->physicsBody()->shape(duckPhysicsShape);
        //
        //	// #2
        ////	_duckNode->physicsBody(PhysicsBody::KinematicBody());
        ////	auto duckPhysicsShape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, _duckNode->mesh().get());
        ////	_duckNode->physicsBody()->shape(duckPhysicsShape);
        //
        // #3
        auto duckPhysicsShape = make_shared<PhysicsShape>(PhysicsShape::Type::ConcavePolyhedron, duckNode);
        duckNode->physicsBody(make_unique<PhysicsBody>(PhysicsBody::Type::Kinematic, duckPhysicsShape));
        //
        // // #4
        // auto duckPhysicsShape = make_shared<PhysicsShape>(PhysicsShape::Type::ConcavePolyhedron, duckNode);
        // duckNode->physicsBody(make_unique<PhysicsBody>(PhysicsBodyType::Kinematic, duckPhysicsShape));

        scene->rootNode()->addChild(duckNode);

        _duckRotator = make_unique<ext::WanderRotator>();

        // preload duck fruit

        auto mesh = util::fs::MeshNamed("cherries_lod/cherries_lod");
        auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        _duckFruit.push_back({mesh, shape, 0.05});

        mesh = util::fs::MeshNamed("orange_lod/orange_lod");
        shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        _duckFruit.push_back({mesh, shape, 0.185});

        mesh = util::fs::MeshNamed("pear_lod/pear_lod");
        shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        _duckFruit.push_back({mesh, shape, 0.24});

        mesh = util::fs::MeshNamed("apple_lod/apple_lod");
        shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        _duckFruit.push_back({mesh, shape, 0.225});

        mesh = util::fs::MeshNamed("banana_lod/banana_lod");
        shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        _duckFruit.push_back({mesh, shape, 0.14});

        mesh = util::fs::MeshNamed("pineapple_lod/pineapple_lod");
        shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        _duckFruit.push_back({mesh, shape, 0.9});

        // add cardboard boxes

        AddCardboardBoxes(*scene);

        auto boxesLight = Light::Spot(Color::LightGray());
        boxesLight->innerAngle(radians(20.0));
        boxesLight->outerAngle(radians(25.0));
        boxesLight->attenuation(Attenuation {.quadratic = 0.035f});
        boxesLight->featheringMode(SpotLight::FeatheringMode::Soft);
        auto boxesLightNode = Node::LightNode(boxesLight);
        boxesLightNode->position({-6.4, 1.2, -2.5});
        boxesLightNode->orientation({0.0999, 0.1969, -0.0202, 0.9751});
        scene->rootNode()->addChild(boxesLightNode);

        auto cameraConfig = _cameraController.config();
        cameraConfig.moveSpeed = math::max(scene->extent());
        _cameraController.config(cameraConfig);

        _window->center();
        _window->open();

        return scene;
    }
    catch (std::exception& e) {
        log::app::f()("Exception: {}", e.what());
        return nullptr;
    }
}

SimulationConfig App::simulationConfig() const {
    return {.timeStep = TIMESTEP};
}

bool App::shouldContinue(const Scene&) {
    return _window->isOpen();
}

void App::inputDidUpdate(Runner&                         runner,
                         Scene&                          scene,
                         InputContext&                   inputContext,
                         const InputContext::UpdateInfo& info) {

    auto& input = static_cast<DesktopInputContext&>(inputContext);

    using Key = DesktopInputContext::Key;
    using MouseButton = DesktopInputContext::MouseButton;
    using DebugOptions = Scene::DebugOptions;

    const auto mouseScrollWheelDelta = input.mouseScrollWheelDelta();

    if (input.keyPressed(Key::Escape)) {
        _window->close();
        log::app::i()("open? {}", _window->isOpen() ? "ya" : "no");
    }

    if (input.keyPressed(Key::Slash)) {
        _window->cursorCaptured(!_window->cursorCaptured());
    }

    auto visualWorld = scene.visualWorld();

    if (!_window->cursorCaptured() && input.mouseButtonPressed(MouseButton::One)) {
        auto mouse = input.mousePosition();
        auto from = scene.visualWorld()->unprojectPoint({mouse.x, mouse.y, 0.0f});
        auto to = scene.visualWorld()->unprojectPoint({mouse.x, mouse.y, 1.0f});
        auto hits =
            scene.physicsWorld()->rayTest(from, to,
                                          PhysicsWorld::RayTestOptions {.searchMode = HitTestSearchMode::All});
        if (!hits.empty()) {
            for (auto& hit : hits) {
                if (auto node = hit.node()) {
                    log::app::i()("HIT node {:p} [{}] at {}, {}, {} ", static_cast<void*>(node.get()),
                                  node->name() ? node->name()->c_str() : "(no name)", hit.worldCoordinates().x,
                                  hit.worldCoordinates().y, hit.worldCoordinates().z);
                }
            }
        }
    }

    if (input.keyPressed(Key::Backslash)) {
        util::snapshot::SaveSnapshot(*_window);
    }

    if (input.keyPressed(Key::H)) {
        // NOTE: once the window is hidden, the scene keeps running but you
        // no longer get key events from the window!
        _window->hidden(!_window->hidden());
    }

    if (input.keyPressed(Key::V)) {
        _window->vSyncEnabled(!_window->vSyncEnabled());
    }

    if (input.keyPressed(Key::R)) {
        if (!_window->recordingGIF()) {
            util::snapshot::StartGIFRecording(*_window, {320, 240}, 8);
        }
        else {
            util::snapshot::StopGIFRecording(*_window);
        }
    }

    if (input.keyPressed(Key::Apostrophe) && visualWorld) {
        if (auto pov = visualWorld->pointOfView().lock()) {
            const auto position = pov->worldPosition();
            const auto orientation = pov->worldOrientation();

            log::app::i()("\ncamera position: ({:.4f}, {:.4f}, {:.4f})\n"
                          "camera orientation: ({:.6f}, {:.6f}, {:.6f}, {:.6f})",
                          position.x, position.y, position.z, orientation.x, orientation.y, orientation.z,
                          orientation.w);
        }
    }

    if (input.keyPressed(Key::L) && visualWorld) {
        if (auto cameraNode = visualWorld->pointOfView().lock()) {
            if (cameraNode->light()) {
                cameraNode->light(nullptr);
            }
            else {
                auto flashLight = Light::Spot();
                flashLight->innerAngle(radians(5.0f));
                flashLight->outerAngle(radians(7.5f));
                flashLight->featheringMode(SpotLight::FeatheringMode::Sharp);
                flashLight->attenuation(Attenuation {.quadratic = 0.001f});
                cameraNode->light(flashLight);
            }
        }
    }

    const auto toggleDebugOption = [&scene](DebugOptions option) {
        const auto options = scene.debugOptions();

        if (util::bitmask::contains(options, option)) {
            scene.debugOptions(util::bitmask::remove(options, option));
        }
        else {
            scene.debugOptions(util::bitmask::add(options, option));
        }
    };

    if (input.keyPressed(Key::F)) {
        toggleDebugOption(DebugOptions::ShowWireframes);
    }

    if (input.keyPressed(Key::B)) {
        toggleDebugOption(DebugOptions::ShowBoundingBoxes);
    }

    if (input.keyPressed(Key::I)) {
        toggleDebugOption(DebugOptions::ShowStatsOverlay);
    }

    if (input.keyPressed(Key::P)) {
        toggleDebugOption(DebugOptions::ShowPhysicsBoundingBoxes);
    }

    if (input.keyPressed(Key::G)) {
        toggleDebugOption(DebugOptions::ShowPhysicsWireframes);
        //scene.physicsWorld()->gravity({10.0f, 0.0f, 0.0f});
    }

    if (input.keyPressed(Key::C)) {
        toggleDebugOption(DebugOptions::ShowPhysicsContactPoints);
    }

    if (input.keyPressed(Key::N)) {
        toggleDebugOption(DebugOptions::ShowPhysicsNormals);
    }

    if (input.keyDown(Key::Z)) {
        this_thread::sleep_for(chrono::milliseconds {8});
    }

    if (mouseScrollWheelDelta.y > 0.0f) {
        auto& runner = App::runner();
        runner.timeScale(math::clamp(runner.timeScale() + mouseScrollWheelDelta.y * 0.1, 0.1, 1.0));
    }

    if (auto pov = scene.visualWorld()->pointOfView().lock(); pov && _window->cursorCaptured()) {
        _cameraController.update(*pov, input, info.deltaTime);
    }
}

void App::sceneWillStep(Runner& runner, Scene& scene, const Scene::StepInfo& info) {

    auto& input = static_cast<DesktopInputContext&>(*scene.inputContext());

    using Key = DesktopInputContext::Key;
    using MouseButton = DesktopInputContext::MouseButton;

    _duckRotator->update(*_duckNode, info.deltaTime);

    if (!_window->cursorCaptured() && input.mouseButtonPressed(MouseButton::Two)) {

        const auto mouse = input.mousePosition();
        const auto from = scene.visualWorld()->unprojectPoint({mouse.x, mouse.y, 0.0f});
        const auto to = scene.visualWorld()->unprojectPoint({mouse.x, mouse.y, 1.0f});

        const auto hits = scene.physicsWorld()->rayTest(from, to);

        if (!hits.empty()) {

            const auto& hit = hits.front();

            if (auto node = hit.node()) {
                if (auto body = node->physicsBody(); body && body->type() == PhysicsBody::Type::Dynamic) {

                    const vec3  direction = normalize(to - from);
                    const float impulse = 5.0f;

                    body->applyForce(direction * impulse, hit.worldCoordinates(), true);
                }
            }
        }
    }

    // if (input.keyPressed(Key::One)) {
    //     _duckNode->physicsBody()->shape()->type(PhysicsShape::Type::BoundingBox);
    // }
    //
    // if (input.keyPressed(Key::Two)) {
    //     _duckNode->physicsBody()->shape()->type(PhysicsShape::Type::ConvexHull);
    // }
    //
    // if (input.keyPressed(Key::Three)) {
    //     _duckNode->physicsBody()->shape()->type(PhysicsShape::Type::ConcavePolyhedron);
    // }

    if (input.keyPressed(Key::Five)) {
        _duckNode->physicsBody()->mass(0.0f);
    }

    if (input.keyPressed(Key::Six)) {
        _duckNode->physicsBody()->mass(10.0f);
    }

    if (input.keyPressed(Key::Seven)) {
        _duckNode->physicsBody()->mass(100.0f);
    }

    if (input.keyPressed(Key::Eight)) {
        for (const auto& node : scene.rootNode()->children(true)) {
            auto body = node->physicsBody();

            if (body && dynamic_pointer_cast<CylinderPhysicsShape>(body->shape())) {

                node->removeFromParent();
            }
        }
    }

    if (input.keyPressed(Key::Nine)) {
        for (const auto& node : scene.rootNode()->children(true)) {
            auto body = node->physicsBody();

            if (body && body->type() == PhysicsBody::Type::Dynamic) {

                node->removeFromParent();
            }
        }
    }

    if (input.keyPressed(Key::GraveAccent)) {
        AddBoxes(scene);
    }

    if (input.keyPressed(Key::Q)) {
        SpawnAutogeneratedPrimitives(scene);
    }

    if (input.keyPressed(Key::M)) {
        SpawnChainMail(scene);
    }

    if (input.keyPressed(Key::O)) {
        SpawnRecursiveTestTree(scene);
    }

    if (input.keyPressed(Key::T)) {
        SpawnHACDTeapot(scene);
    }

    if (input.keyPressed(Key::U)) {
        AddRing(scene);
    }

    const bool duckFruitPressed = input.keyPressed(Key::Tab);

    const bool duckFruitActive = duckFruitPressed || input.keyDown(Key::Tab);

    if (duckFruitPressed) {
        _duckFruitTrigger.reset();
    }

    if (_duckNode && duckFruitActive) {
        _duckFruitTrigger.update(info.startTime, [&] {
            SpawnDuckFruit(scene, *_duckNode, _duckFruit);
        });
    }
    else {
        _duckFruitTrigger.reset();
    }

    const bool singleShotRequested = input.mouseButtonPressed(MouseButton::One);
    const bool continuousShotPressed = input.mouseButtonPressed(MouseButton::Two);
    const bool continuousShotActive = continuousShotPressed || input.mouseButtonDown(MouseButton::Two);

    if (continuousShotPressed) {
        _slurmTrigger.reset();
    }

    shared_ptr<Node> pointOfView;

    if (_window->cursorCaptured() && (singleShotRequested || continuousShotActive)) {

        if (auto visualWorld = scene.visualWorld()) {
            pointOfView = visualWorld->pointOfView().lock();
        }
    }

    if (singleShotRequested && pointOfView) {
        ShootSlurm(scene, pointOfView->worldPosition(), pointOfView->worldForward());
    }

    if (continuousShotActive && pointOfView) {
        _slurmTrigger.update(info.startTime, [&] {
            ShootSlurm(scene, pointOfView->worldPosition(), pointOfView->worldForward());
        });
    }
    else {
        _slurmTrigger.reset();
    }
}

/// Private Static Non-Member Functions ///

// small complex physics shapes fall through the floor easily even with aggressive CCD
void SpawnDuckFruit(Scene& scene, const Node& duckNode, vector<App::DuckFruitDef>& duckFruit) {

    auto fruit = duckFruit[uniform_linear(0, 5)];

    shared_ptr<Node>         node = Node::MeshNode(get<0>(fruit));
    shared_ptr<PhysicsShape> physicsShape = get<1>(fruit);
    float                    mass = get<2>(fruit);

    // add local offset to duck, then convert that position to world space,
    // then attach to root node (below)
    node->transform(duckNode.worldTransform() * translate(mat4(1.0), vec3(0.0, 3.25, 0.2)));

    auto physicsBody = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, physicsShape);
    physicsBody->mass(mass);
    physicsBody->restitution(0.25);
    physicsBody->friction(1.0);

    // ! NOTE ! convex hulls do not work well for CCD, at least not as smalls scales.
    // TODO: switch to primitive colliders for fruit.
    auto        extent = node->mesh()->localExtent();
    const float minExtent = std::min({extent.x, extent.y, extent.z});
    const float ccdRadius = minExtent * 0.5f;
    physicsBody->ccdMotionThreshold(ccdRadius * 0.1f);
    physicsBody->ccdSweptSphereRadius(ccdRadius);
    physicsBody->ccdEnabled(true);

    // fruit starting orientation
    float heading = uniform_linear(0.0f, two_pi());
    float pitch = uniform_linear(0.0f, two_pi());
    float roll = uniform_linear(0.0f, two_pi());
    node->eulerAngles({heading, pitch, roll});

    // fruit linear velocity

    float lvX = uniform_n11() * 2.0f;
    float lvY = uniform_linear(1.0f, 10.0f);
    float lvZ = uniform_n11() * 2.0f;
    auto  direction = duckNode.worldOrientation() * vec3 {lvX, lvY, lvZ};
    physicsBody->linearVelocity(direction);

    // fruit spin
    const float ANGULAR_VARIANCE = radians(60.0); // deg/sec
    physicsBody->angularVelocity({uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
                                  uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
                                  uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE)});

    node->physicsBody(std::move(physicsBody));

    scene.rootNode()->addChild(node);
}

// works well, simple colliders
// void SpawnDuckFruit(Scene& scene, const Node& duckNode) {
//
// 	static const float SPAWN_RATE = 10.0f; // pieces/sec
//
// 	util::flow::every(chrono::duration<float>(1.0f / SPAWN_RATE), [&] {
//
// 		log::d()("Spawning duck fruit.");
//
// 		auto duckFruit = _duckFruit[uniform_linear(0, 5)];
//
// 		shared_ptr<Node> node = Node::MeshNode(get<0>(duckFruit));
//
// 		// TEST: shared primitive shape reused by all spawned fruit.
// 		// If this works, shared PhysicsShape reuse is probably fine, and the
// 		// fruit ConvexHull shape path is the problem.
// 		static auto sharedSphereShape = make_shared<SpherePhysicsShape>(0.25f);
// 		shared_ptr<PhysicsShape> physicsShape = sharedSphereShape;
//
// 		float mass = get<2>(duckFruit);
//
// 		// add local offset to duck, then convert that position to world space,
// 		// then attach to root node (below)
// 		node->transform(duckNode.worldTransform() * translate(mat4(1.0f), vec3(0.0f, 3.25f, 0.2f)));
//
// 		auto physicsBody = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, physicsShape);
// 		physicsBody->mass(mass);
// 		physicsBody->restitution(0.25f);
// 		physicsBody->friction(1.0f);
//
// 		// Fixed CCD values for this test. Do not derive from the visual mesh here.
// 		physicsBody->ccdMotionThreshold(0.001f);
// 		physicsBody->ccdSweptSphereRadius(0.20f);
// 		physicsBody->ccdEnabled(true);
//
// 		// fruit starting orientation
// 		float heading = uniform_linear(0.0f, two_pi());
// 		float pitch = uniform_linear(0.0f, two_pi());
// 		float roll = uniform_linear(0.0f, two_pi());
// 		node->eulerAngles({heading, pitch, roll});
//
// 		// fruit linear velocity
// 		float lvX = uniform_n11() * 2.0f;
// 		float lvY = uniform_linear(1.0f, 10.0f);
// 		float lvZ = uniform_n11() * 2.0f;
// 		auto direction = duckNode.worldOrientation() * vec3{lvX, lvY, lvZ};
// 		physicsBody->linearVelocity(direction);
//
// 		// fruit spin
// 		const float ANGULAR_VARIANCE = radians(60.0f); // deg/sec
// 		physicsBody->angularVelocity({
// 			uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
// 			uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
// 			uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE)
// 		});
//
// 		node->physicsBody(std::move(physicsBody));
//
// 		scene.rootNode()->addChild(node);
// 	});
// }

void ShootSlurm(Scene& scene, const vec3& location, const vec3& direction) {

    static auto mesh = util::fs::MeshNamed("slurm/slurm");
    mesh->materials()[0]->emission(mesh->materials()[0]->diffuse());
    mesh->materials()[1]->emission(mesh->materials()[1]->diffuse());

    auto node = Node::MeshNode(mesh);
    node->name("Slurm");

    node->position(location);

    //static auto extent = node->mesh()->worldExtent(node->worldTransform());
    static auto extent = node->mesh()->localExtent();
    static auto physicsShape = make_shared<CylinderPhysicsShape>(extent.x / 2.0, extent.y);
    auto        physicsBody = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, physicsShape);
    physicsBody->mass(.354); // 12fl oz water @ 70F
    physicsBody->restitution(1.0);
    physicsBody->friction(0.35);
    physicsBody->rollingFriction(0.05);

    const float radius = extent.x * 0.5f;
    physicsBody->ccdMotionThreshold(radius * 0.25f);
    physicsBody->ccdSweptSphereRadius(radius * 0.8f);
    physicsBody->ccdEnabled(true);

    static auto light = Light::Point();
    light->attenuation(Attenuation {.quadratic = 0.04f});
    node->light(light);

    // add random factor

    node->eulerAngles({uniform_linear(0.0f, two_pi()), uniform_linear(0.0f, two_pi()),
                       uniform_linear(0.0f, two_pi())});

    static const float ANGULAR_VARIANCE = radians(260.0); // deg/sec
    physicsBody->angularVelocity({uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
                                  uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
                                  uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE)});

    const float        VELOCITY = uniform_linear(40.0f, 60.0f);
    static const float DIRECTION_VARIATION = 0.01;
    const vec3         variedDirection = normalize(normalize(direction) + uniform_ball(DIRECTION_VARIATION));
    physicsBody->linearVelocity(variedDirection * VELOCITY);

    node->physicsBody(std::move(physicsBody));

    scene.rootNode()->addChild(node);
}

// this is super fudgecycle
shared_ptr<Node> Hula(float minorRadius, float majorRadius) {

    static auto ringPhysicsNode = Node::NamedNode("Ring physics shape node");

    static const float CAPSULE_RADIUS = .1;
    static const float TORUS_MID_RADIUS = majorRadius - (majorRadius - minorRadius); // ! cap len??
    static const float CAPSULE_HEIGHT = (math::two_pi() * TORUS_MID_RADIUS) / 8.0f;
    static const auto  visualMesh = Capsule::Mesh(CAPSULE_RADIUS, CAPSULE_HEIGHT, 16, 16, 16);

    for (int s = 0; s < 8; ++s) {

        float angle = (float) (math::two_pi() / 8.0) * (float) s;

        auto partNode = Node::NamedNode("Ring capsule part node " + to_string(s + 1));
        partNode->mesh(visualMesh);

        quat rotation = quaternion(vec3(0, 0, 1), angle);
        mat4 rotMatrix = mat4_cast(rotation);
        mat4 translation = translate(mat4(1.0f), vec3(1.6, 0, 0)); // ! RADIUS
        mat4 transform = rotMatrix * translation;
        partNode->transform(transform);

        //partNode->hidden(true);

        ringPhysicsNode->addChild(partNode);
    }

    static const auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, ringPhysicsNode);

    auto torusMesh =
        Torus::Mesh(minorRadius + (minorRadius / 32.0f), majorRadius + (majorRadius / 32.0f), 128, 128);
    auto ringVisualNode = Node::MeshNode(torusMesh);

    auto colorProperty = Color::LightGray();
    auto colorMaterial = make_shared<Material>(monostate {}, colorProperty, monostate {});
    torusMesh->addMaterial(colorMaterial);

    auto body = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
    body->momentOfInertia({0, 0, 0});
    //body->affectedByGravity(false);
    ringVisualNode->physicsBody(std::move(body));

    return ringVisualNode;
}

void AddBox(Scene& scene, const vec3& location, shared_ptr<Color> color) {

    auto node = Node::MeshNode(Box::Mesh(1.0, 1.0, 1.0));
    node->name("Box");
    auto material = make_shared<Material>(monostate {}, monostate {}, monostate {}, color);
    node->mesh()->addMaterial(material);
    node->position(location);

    auto light = Light::Point(color);
    light->attenuation(Attenuation {.quadratic = 0.04f});
    node->light(light);

    auto physicsBody = PhysicsBody::DynamicBody();
    physicsBody->mass(1.0);
    physicsBody->restitution(0.1);
    physicsBody->friction(0.25);

    static auto physicsShape = make_shared<PhysicsShape>(PhysicsShape::Type::BoundingBox, node->mesh());
    physicsBody->shape(physicsShape);

    node->physicsBody(std::move(physicsBody));

    scene.rootNode()->addChild(node);
}

void AddCardboardBox(Scene& scene, const vec3& location, const vec3& axis, float angle) {

    static auto mesh = util::fs::MeshNamed("cardboard_box/cardboard_box");

    auto node = Node::MeshNode(mesh);
    node->name("Cardboard Box");

    node->position(location);
    node->rotation(axis, angle);

    auto        physicsBody = PhysicsBody::DynamicBody();
    static auto phyicsShape = make_shared<PhysicsShape>(PhysicsShape::Type::BoundingBox, node->mesh());
    physicsBody->shape(phyicsShape);

    physicsBody->mass(0.1);
    physicsBody->restitution(0.1);
    physicsBody->friction(0.5);
    node->physicsBody(std::move(physicsBody));

    scene.rootNode()->addChild(node);
}

void SpawnHACDTeapot(Scene& scene) {

    auto teapotNode = Node::MeshNode(util::fs::MeshNamed("teapot/teapot"));

    ConvexDecomposer::Options options;
    options.maxConvexHulls = options.maxConvexHulls / 2;
    options.resolution = options.resolution / 2;
    options.maxRecursionDepth = options.maxRecursionDepth / 2;
    options.maxNumVerticesPerHull = options.maxNumVerticesPerHull / 2;

    auto decomposedElements = vector<unique_ptr<MeshElement>>();

    for (auto& element : teapotNode->mesh()->elements()) {
        auto decomposer = ConvexDecomposer(*element, options);
        auto elements = decomposer.decompose();

        decomposedElements.insert(decomposedElements.end(), make_move_iterator(elements.begin()),
                                  make_move_iterator(elements.end()));
    }

    auto decomposedTeapotMaterials = vector<shared_ptr<Material>>();
    decomposedTeapotMaterials.reserve(decomposedElements.size());
    for (int m = 0; m < decomposedElements.size(); ++m) {
        auto randomColorProperty = Color::Random();
        decomposedTeapotMaterials.push_back(make_shared<Material>(monostate {}, monostate {}, monostate {},
                                                                  randomColorProperty));
    }

    auto hacdTeapotMesh = make_shared<Mesh>(decomposedElements, decomposedTeapotMaterials);
    auto decomposedTeapotNode = Node::MeshNode(hacdTeapotMesh);
    decomposedTeapotNode->name("A Goddamn Teapot.");
    decomposedTeapotNode->scale(decomposedTeapotNode->scale() * 20.0f);
    decomposedTeapotNode->position({0, 10, 0});
    scene.rootNode()->addChild(decomposedTeapotNode);
}

void AddBoxes(Scene& scene) {

    // 16 items
    static const int   OBJECT_ARRAY_SIZE_X = 2;
    static const int   OBJECT_ARRAY_SIZE_Y = 4;
    static const int   OBJECT_ARRAY_SIZE_Z = 2;
    static const float X_OFFSET = -10.0;
    static const float Z_OFFSET = 10.0;

    int SPACING = 1.0;
    int DROP_HEIGHT = 40.0;
    int colorIndex = 0;
    for (int k = 0; k < OBJECT_ARRAY_SIZE_Y; ++k) {
        for (int i = 0; i < OBJECT_ARRAY_SIZE_X; ++i) {
            for (int j = 0; j < OBJECT_ARRAY_SIZE_Z; ++j) {
                vec3 position = vec3(SPACING * i - (OBJECT_ARRAY_SIZE_X / 2.0) + X_OFFSET,
                                     DROP_HEIGHT + SPACING * k - (OBJECT_ARRAY_SIZE_Y / 2.0),
                                     SPACING * j - (OBJECT_ARRAY_SIZE_Z / 2.0) + Z_OFFSET);
                AddBox(scene, position, Color::Random());
            }
        }
    }
}

void AddCardboardBoxes(Scene& scene) {

    constexpr int HEIGHT = 7;

    static const vec3  AXIS = {0, 1, 0};
    static const float ANGLE = radians(25.0);

    static const float X_BASE = -15.0;
    static const float Y_BASE = 0.5;
    static const float Z_BASE = -10.0;

    static const float X_OFFSET = 0.75;
    static const float Y_OFFSET = 1.5;
    static const float Z_OFFSET = -0.36;

    for (int r = 0; r < HEIGHT; ++r) {
        float x = X_BASE + (X_OFFSET * r);
        float y = Y_BASE + (Y_OFFSET * r);
        float z = Z_BASE + (Z_OFFSET * r);

        for (int i = 0; i < HEIGHT - r; ++i) {
            AddCardboardBox(scene, {x, y, z}, AXIS, ANGLE);
            x += 1.5;
            z -= 0.75;
        }
    }
}

void AddRing(Scene& scene) {

    auto        node = Node::NamedNode("Torus Node");
    static auto mesh = Torus::Mesh(.75, 1.0, 16, 16);
    static auto physicsShape = make_shared<PhysicsShape>(PhysicsShape::Type::ConcavePolyhedron, mesh);
    //auto physicsBody = PhysicsBody::DynamicBody();
    auto physicsBody = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, physicsShape);
    node->mesh(mesh);
    static auto materialProperty = Color::Yellow();
    static auto material = make_shared<Material>(monostate {}, materialProperty, monostate {});
    node->mesh()->addMaterial(material);
    node->physicsBody(std::move(physicsBody));
    node->position({0, 15, 0});
    scene.rootNode()->addChild(node);
}

shared_ptr<Node> ColoredSphereNode(shared_ptr<Color> color, string name) {

    auto sphereMesh = Sphere::Mesh(.25, 8);

    auto colorMaterial = make_shared<Material>(monostate {}, color, monostate {});

    sphereMesh->addMaterial(colorMaterial);

    auto node = Node::MeshNode(sphereMesh);
    node->name(name);

    return node;
}

void SpawnRecursiveTestTree(Scene& scene) {

    /*
	Node "a" [Shape]
	- Mesh [White]

		Node "b" [x: 5]
		- Mesh [Green]

			Node "c" [x: 5]
			- Mesh [Blue]

				Node "d" [x: 5]
				- Mesh [Yellow]

		Node "e" [y: 5]
		- Mesh [Orange]

			Node "f" [y: 5]
			- Mesh [Purple]

				Node "g" [y: 5]
				- Mesh [Lime]

		Node "h" [z: -5]
		- Mesh [Magenta]

			Node "i" [z: -5]
			- Mesh [Cyan]

				Node "j" [z: -5]
				- Mesh [Teal] */

    auto a = ColoredSphereNode(Color::White(), "a");
    auto b = ColoredSphereNode(Color::Green(), "b");
    auto c = ColoredSphereNode(Color::Blue(), "c");
    auto d = ColoredSphereNode(Color::Yellow(), "d");
    auto e = ColoredSphereNode(Color::Orange(), "e");
    auto f = ColoredSphereNode(Color::Purple(), "f");
    auto g = ColoredSphereNode(Color::Lime(), "g");
    auto h = ColoredSphereNode(Color::Magenta(), "h");
    auto i = ColoredSphereNode(Color::Cyan(), "i");
    auto j = ColoredSphereNode(Color::Teal(), "j");

    a->addChild(b);
    b->addChild(c);
    c->addChild(d);

    a->addChild(e);
    e->addChild(f);
    f->addChild(g);

    a->addChild(h);
    h->addChild(i);
    i->addChild(j);

    a->position({0, 15, 0});

    b->position({5, 0, 0});
    c->position({5, 0, 0});
    d->position({5, 0, 0});

    e->position({0, 5, 0});
    f->position({0, 5, 0});
    g->position({0, 5, 0});

    h->position({0, 0, -5});
    i->position({0, 0, -5});
    j->position({0, 0, -5});

    auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, a);
    auto physicsBody = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
    a->physicsBody(std::move(physicsBody));

    scene.rootNode()->addChild(a);
}

void SpawnAutogeneratedPrimitives(Scene& scene) {

    { // box
        auto mesh = Box::Mesh(1, 1, 1);
        auto node = Node::MeshNode(mesh);
        auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        auto body = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
        node->physicsBody(std::move(body));
        node->position({5, 0, 0});
        node->position({node->position().x, node->position().y + 10, node->position().y});

        scene.rootNode()->addChild(node);
    }

    { // capsule
        auto mesh = Capsule::Mesh(.5, 2, 8, 8, 8);
        auto node = Node::MeshNode(mesh);
        auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        auto body = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
        node->physicsBody(std::move(body));
        node->position({0, 5, 0});
        node->position({node->position().x, node->position().y + 10, node->position().y});

        scene.rootNode()->addChild(node);
    }

    { // cone
        auto mesh = Cone::Mesh(1, 1, 8, 8);
        auto node = Node::MeshNode(mesh);
        auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        auto body = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
        node->physicsBody(std::move(body));
        node->position({0, 0, -5});
        node->position({node->position().x, node->position().y + 10, node->position().y});

        scene.rootNode()->addChild(node);
    }

    { // cylinder
        auto mesh = Cylinder::Mesh(.5, 1, 8, 8);
        auto node = Node::MeshNode(mesh);
        auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        auto body = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
        node->physicsBody(std::move(body));
        node->position({-5, 0, 0});
        node->position({node->position().x, node->position().y + 10, node->position().y});

        scene.rootNode()->addChild(node);
    }

    { // plane
        auto mesh = Plane::Mesh(1, 1);
        auto node = Node::MeshNode(mesh);
        auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        auto body = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
        node->physicsBody(std::move(body));
        node->position({0, -5, 0});
        node->position({node->position().x, node->position().y + 10, node->position().y});

        scene.rootNode()->addChild(node);
    }

    { // sphere
        auto mesh = Sphere::Mesh(1, 8);
        auto node = Node::MeshNode(mesh);
        auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, mesh);
        auto body = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
        node->physicsBody(std::move(body));
        node->position({0, 0, 5});
        node->position({node->position().x, node->position().y + 10, node->position().y});

        scene.rootNode()->addChild(node);
    }
}

void SpawnInvisiblePrimitives(Scene& scene) {

    //	{ // box
    //		auto node = Node::NamedNode("Box physics shape node");
    //		auto shape = make_shared<BoxPhysicsShape>(1, 1, 1);
    //		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
    //		node->physicsBody(body);
    //		node->position({5, 0, 0});
    //		node->position({node->position().x, node->position().y+10, node->position().y});
    //
    //		scene.rootNode()->addChild(node);
    //	}
    //
    //	{ // capsule
    //
    //		auto node = Node::NamedNode("Capsule physics shape node");
    //		auto shape = make_shared<CapsulePhysicsShape>(.5, 2);
    //		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
    //		node->physicsBody(body);
    //		node->position({0, 5, 0});
    //		node->position({node->position().x, node->position().y+10, node->position().y});
    //
    //		scene.rootNode()->addChild(node);
    //	}
    //
    //	{ // cone
    //		auto node = Node::NamedNode("Cone physics shape node");
    //		auto shape = make_shared<ConePhysicsShape>(1, 1);
    //		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
    //		node->physicsBody(body);
    //		node->position({0, 0, -5});
    //		node->position({node->position().x, node->position().y+10, node->position().y});
    //
    //		scene.rootNode()->addChild(node);
    //	}
    //
    //	{ // cylinder
    //		auto node = Node::NamedNode("Cylinder physics shape node");
    //		auto shape = make_shared<CylinderPhysicsShape>(.5, 1);
    //		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
    //		node->physicsBody(body);
    //		node->position({-5, 0, 0});
    //		node->position({node->position().x, node->position().y+10, node->position().y});
    //
    //		scene.rootNode()->addChild(node);
    //	}
    //
    //	{ // plane
    //		auto node = Node::NamedNode("Plane physics shape node");
    //		auto shape = make_shared<PlanePhysicsShape>(1, 1);
    //		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
    //		node->physicsBody(body);
    //		node->position({0, -5, 0});
    //		node->position({node->position().x, node->position().y+10, node->position().y});
    //
    //		scene.rootNode()->addChild(node);
    //	}

    { // sphere
        auto node = Node::NamedNode("Sphere physics shape node");
        auto shape = make_shared<SpherePhysicsShape>(1);
        auto body = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
        node->physicsBody(std::move(body));
        node->position({0, 0, 5});
        node->position({node->position().x, node->position().y + 10, node->position().y});

        scene.rootNode()->addChild(node);

        //		testNode = node;
    }
}

shared_ptr<Node> ChainmailLink(float minorRadius, float majorRadius) {

    static auto ringPhysicsNode = Node::NamedNode("Ring physics shape node");

    static const float CAPSULE_RADIUS = .1;
    static const float TORUS_MID_RADIUS = majorRadius - (majorRadius - minorRadius);
    static const float CAPSULE_HEIGHT = (math::two_pi() * TORUS_MID_RADIUS) / 8.0f;
    static const auto  visualMesh = Capsule::Mesh(CAPSULE_RADIUS, CAPSULE_HEIGHT, 16, 16, 16);

    for (int s = 0; s < 8; ++s) {

        float angle = (float) (math::two_pi() / 8.0) * (float) s;

        auto partNode = Node::NamedNode("Ring capsule part node " + to_string(s + 1));
        partNode->mesh(visualMesh);

        quat rotation = quaternion(vec3(0, 0, 1), angle);
        mat4 rotMatrix = mat4_cast(rotation);
        mat4 translation = translate(mat4(1.0f), vec3(1, 0, 0));
        mat4 transform = rotMatrix * translation;
        partNode->transform(transform);

        //partNode->hidden(true);

        ringPhysicsNode->addChild(partNode);
    }

    static const auto shape = make_shared<PhysicsShape>(PhysicsShape::Type::ConvexHull, ringPhysicsNode);

    auto torusMesh =
        Torus::Mesh(minorRadius + (minorRadius / 32.0f), majorRadius + (majorRadius / 32.0f), 128, 128);
    auto ringVisualNode = Node::MeshNode(torusMesh);

    auto colorProperty = Color::LightGray();
    auto colorMaterial = make_shared<Material>(monostate {}, colorProperty, monostate {});
    torusMesh->addMaterial(colorMaterial);

    auto body = make_unique<PhysicsBody>(PhysicsBody::Type::Dynamic, shape);
    //body->affectedByGravity(false);
    ringVisualNode->physicsBody(std::move(body));

    ringVisualNode->position({0, 1, 0});

    //	scene.rootNode()->addChild(ringVisualNode);
    return ringVisualNode;
}

void SpawnChainMail(Scene& scene) {

    static const float PI = 3.14159265358;

    static const float TORUS_MINOR_RADIUS = .9;
    static const float TORUS_MAJOR_RADIUS = 1;

    static const int CHAINMAIL_WIDTH = 3;
    static const int CHAINMAIL_HEIGHT = 4;

    static const int GROUND_OFFSET = 35;

    auto chainmailNode = Node::NamedNode("chainmail");

    // horizontal chain
    for (int w = 0; w < CHAINMAIL_WIDTH; ++w) {
        for (int h = 0; h < CHAINMAIL_HEIGHT; ++h) {
            auto link = ChainmailLink(TORUS_MINOR_RADIUS, TORUS_MAJOR_RADIUS);
            //		link->rotation({1, 0, 0}, (float) (w % 2 == 0 ? (PI / 6.0) : (-PI / 6.0)));
            //			link->rotation({1, 0, 0}, PI / 6.0);
            float rotation = PI / 12.0;
            float wStagger = 0;
            if (h % 2 == 0) {
                rotation = -PI / 12.0;
                wStagger = TORUS_MAJOR_RADIUS * 1.15f;
            }
            link->rotation({1, 0, 0}, rotation);
            //link->rotation({1, 0, 0}, (float)(h%2 == 0 ? (PI/6.0) : (-PI/6.0)));
            //auto stagger = (w%2 == 0 ? 0 : TORUS_MAJOR_RADIUS);
            auto stagger = 0;
            link->position(vec3(((((2 * TORUS_MAJOR_RADIUS) * 1.15) * w) + wStagger),
                                /*GROUND_OFFSET*/ 0 + ((1 * TORUS_MAJOR_RADIUS) * 1.15) * h, 0));
            chainmailNode->addChild(link);
            //scene.rootNode()->addChild(link);
        }
    }

    chainmailNode->rotation({1, 0, 0}, pi_over_2());
    chainmailNode->position({-chainmailNode->extent().x / 2.0f + 1.0f, GROUND_OFFSET,
                             -chainmailNode->extent().z / 2.0f + 1.0f});
    scene.rootNode()->addChild(chainmailNode);
}
