//
//  main.cpp
//  avara3d
//
//  Created by Morgan Davis on 11/19/17.
//  Copyright © 2024 Morgan K Davis. All rights reserved.
//

#include <functional>
#include <memory>
#include <string>
#include <thread>
#include <tuple>
#include <utility>
#include <vector>

#include "a3d/a3d.h"
#include "a3d/Utilities.h"

// testing
#include "a3d/physics/ConvexDecomposer.h"

using namespace a3d;
using namespace a3d::math;
using namespace std;
using namespace std::placeholders;

const LogLevel				APP_LOG_LEVEL 			{LogLevel::Debug};
const uvec2					WINDOW_SIZE 			{1280, 768};
const bool					FULLSCREEN 				{false};
const bool					ENABLE_HIGH_DPI			{true};
const AntialiasingMode		AA_MODE					{AntialiasingMode::Msaa16X};
const bool					ENABLE_VSYNC			{false};
const bool					USE_DEFAULT_LIGHTING	{false};
const bool					CAPTURE_CURSOR			{false};
const float					MOUSE_SENSITIVITY		{0.5};
const float					PHYSICS_TIMESTEP		{1.0/128.0};

void UpdateCallback(Scene& scene, double time, double deltaTime);
void WillRenderCallback(VisualWorld& world, double time, double deltaTime);
void DidRenderCallback(VisualWorld& world, double time, double deltaTime);
void DidSimulatePhysicsCallback(PhysicalWorld& world, double time, double deltaTime);

void InitLog();
void LogBuildInfo();
void SpawnDuckFruit(Scene& scene, Node& duckNode);
void ShootSlurm(Scene& scene, const vec3& location, const vec3& direction);
void AddCardboardBox(Scene& scene, const vec3& location, const vec3& axis, float angle);
void SpawnHACDTeapot(Scene& scene);
void AddBoxes(Scene& scene);
void AddCardboardBoxes(Scene& scene);
void AddRing(Scene& scene);
shared_ptr<Node> ColoredSphereNode(shared_ptr<Color> color, string name);
void SpawnRecursiveTestTree(Scene& scene);
void SpawnAutogeneratedPrimitives(Scene& scene);
void SpawnInvisiblePrimitives(Scene& scene);
shared_ptr<Node> ChainmailLink(float minorRadius, float majorRadius);
void SpawnChainMail(Scene& scene);

Node*	g_palmNode;
Node*	g_duckNode;



vector<tuple<shared_ptr<Mesh>, shared_ptr<PhysicsShape>, float>>* g_duckFruit{};



// TODO: put this somewhere.
struct WanderRotate {
	// tunables
	float minInterval = 0.8f; // seconds
	float maxInterval = 2.5f; // seconds
	float minSpeed  = 0.5f; // rad/s
	float maxSpeed  = 1.0f; // rad/s
	float smoothing = 1.0f; // bigger = snappier

	// state
	float timer = 0.0f;
	float nextChange = 1.0f;

	vec3 angularVelocity = {0, 0, 0}; // current rad/s (axis * speed)
	vec3 targetAngularVelocity = {0, 0, 0}; // desired rad/s

	void chooseNewTarget() {
		vec3 axis = uniform_spherical(1.0);
		float speed = uniform_linear(minSpeed, maxSpeed);
		targetAngularVelocity = axis * speed;
		nextChange = uniform_linear(minInterval, maxInterval);
		timer = 0.0f;
	}

	void update(Node& n, float dt) {
		timer += dt;
		if (timer >= nextChange) chooseNewTarget();

		// exponential smoothing toward target
		// alpha = 1 - exp(-smoothing * dt)  (frame-rate independent)
		float alpha = 1.0f - math::exp(-smoothing * dt);
		angularVelocity = angularVelocity + (targetAngularVelocity - angularVelocity) * alpha;

		// integrate into orientation
		float angle = length(angularVelocity) * dt;
		if (angle > 1e-6f) {
			vec3 axis = normalize(angularVelocity);
			quat dq = math::quaternion(axis, angle); // implement or use yours
			n.orientation(normalize(dq * n.orientation())); // or n.rotation *= dq depending on convention
		}
	}
};

WanderRotate* wr;




int main(int argc, const char* argv[]) {

	try {

		InitLog();
		LogBuildInfo();

		auto window = make_unique<GLFWWindow>(RenderingApi::OpenGL,
											  *utils::ExecutableName(),
											  WINDOW_SIZE,
											  FULLSCREEN,
											  ENABLE_HIGH_DPI,
											  AA_MODE);
		window->vSyncEnabled(ENABLE_VSYNC);
		window->cursorCaptured(CAPTURE_CURSOR);

		auto inputManager = make_unique<GLFWInputManager>(window.get());

		auto visualWorld = make_unique<VisualWorld>(*window);
		visualWorld->fogStartDistance(50.0);
		visualWorld->fogEndDistance(400.0);
		visualWorld->fogDensityExponent(1.0);
		visualWorld->fogColor(Color::DarkGray());
		MaterialProperty background = Color::Black();
//		MaterialProperty background = make_shared<Texture>(utils::CubeImageNamed("stormy", "png"));
		visualWorld->background(background);
		visualWorld->willRenderCallback(bind(&WillRenderCallback, _1, _2, _3));
		visualWorld->didRenderCallback(bind(&DidRenderCallback, _1, _2, _3));

		auto physicalWorld = make_unique<PhysicalWorld>();
		physicalWorld->timestep(PHYSICS_TIMESTEP);
		physicalWorld->didSimulateCallback(bind(&DidSimulatePhysicsCallback, _1, _2, _3));

		auto scene = make_unique<Scene>(std::move(visualWorld),
										std::move(physicalWorld),
										std::move(inputManager));
		scene->debugOptions(DebugOptions::ShowStatsOverlay);
		scene->updateCallback(bind(&UpdateCallback, _1, _2, _3));

		//scene->visualWorld()->usesDefaultLighting(true);


		// ambient light

		auto ambientColor = make_shared<Color>(.1f);
		auto ambientLight = make_shared<AmbientLight>(ambientColor);
		auto ambientLightNode = Node::LightNode(ambientLight);
		scene->rootNode()->addChild(ambientLightNode);



		// directional light

		auto sunColor = Color::Gray();
		auto sunLight = make_shared<DirectionalLight>(sunColor);
		auto sunNode = Node::LightNode(sunLight);
		sunNode->eulerAngles({radians(0.0f),
							  radians(45.0),
							  radians(0.0)});
		scene->rootNode()->addChild(sunNode);


			//pointLightNode->mesh(Box::Mesh(0.5, 0.5, 0.5));
		//}

		// box
	//	const float BOX_DIM = 10.0;
	//	auto boxNode = make_shared<Node>("Box node");
	//	boxNode->mesh(make_shared<Box>(BOX_DIM, BOX_DIM, BOX_DIM));
	//	auto boxImage = ImageNamed("grid10");
	//	//auto gridImage = ImageNamed("grid10_512");
	//	auto boxMaterialProperty = make_shared<MaterialProperty>(boxImage);
	//	boxMaterialProperty->wrapS(WRAP_MODE::REPEAT);
	//	boxMaterialProperty->wrapT(WRAP_MODE::REPEAT);
	//	boxMaterialProperty->maxAnisotropy(16);
	//	boxMaterialProperty->minificationFilter(FILTER_MODE::LINEAR_MIPMAP_LINEAR);
	//	boxMaterialProperty->magnificationFilter(FILTER_MODE::LINEAR);
	//	auto boxMaterial = make_shared<Material>(nullptr, boxMaterialProperty, nullptr);
	//	boxMaterial->uvScale(BOX_DIM/10.0);
	//	boxMaterial->doubleSided(true);
	//	boxNode->mesh()->addMaterial(boxMaterial);
	//	boxNode->position({-20, 0, 20});
	//
	//	auto boxPhysicsBody = PhysicsBody::StaticBody();
	//	boxPhysicsBody->mass(0);
	//	boxPhysicsBody->friction(1);
	//	boxPhysicsBody->restitution(0.25);
	//	boxNode->physicsBody(boxPhysicsBody);
	//
	//	scene->rootNode()->addChild(boxNode);




		// ground plane

//		const float PLANE_LENGTH = 50.0;
//		const float PLANE_WIDTH = 50.0;
//		auto planeNode = Node::NamedNode("Ground plane node");
//		planeNode->mesh(Box::Mesh(PLANE_LENGTH, PLANE_WIDTH, 1));
//		auto gridImage = DARK ? utils::ImageNamed("grid10")->inverted() : utils::ImageNamed("grid10");
//		auto planeTexture = make_shared<Texture>(std::move(gridImage));
//		planeTexture->sampler()->wrapS(WrapMode::Repeat);
//		planeTexture->sampler()->wrapT(WrapMode::Repeat);
//		planeTexture->sampler()->maxAnisotropy(16);
//		planeTexture->sampler()->minificationFilter(FilterMode::LinearMipmapLinear);
//		planeTexture->sampler()->magnificationFilter(FilterMode::Linear);
//		shared_ptr<Material> planeMaterial = nullptr;
//		if (DARK) {
//			planeMaterial = make_shared<Material>(monostate{},
//												  monostate{},
//												  monostate{},
//												  planeTexture);
//		}
//		else {
//			planeMaterial = make_shared<Material>(monostate{},
//												  planeTexture,
//												  Color::Gray());
//		}



		static const float PLANE_LENGTH = 50.0;
		static const float PLANE_WIDTH = 50.0;
		auto planeNode = Node::NamedNode("Ground plane node");
		planeNode->mesh(Box::Mesh(PLANE_LENGTH, PLANE_WIDTH, 0));
		//auto gridImage = DARK ? utils::ImageNamed("grid10")->inverted() : utils::ImageNamed("grid10");
//		auto planeTexture = make_shared<Texture>(Color::White());
//		planeTexture->sampler()->wrapS(WrapMode::Repeat);
//		planeTexture->sampler()->wrapT(WrapMode::Repeat);
//		planeTexture->sampler()->maxAnisotropy(16);
//		planeTexture->sampler()->minificationFilter(FilterMode::LinearMipmapLinear);
//		planeTexture->sampler()->magnificationFilter(FilterMode::Linear);

		shared_ptr<Material> planeMaterial = make_shared<Material>(monostate{},
																   Color::DarkGray(),
																   Color::LightGray());
		planeMaterial->locksAmbientWithDiffuse(false);
//		}
//		else {
//			planeMaterial = make_shared<Material>(monostate{},
//												  planeTexture,
//												  Color::Gray());
//		}



		planeMaterial->uvScale(PLANE_LENGTH / 10.0);
		planeMaterial->doubleSided(false);
		planeNode->mesh()->addMaterial(planeMaterial);
		planeNode->rotation({1, 0, 0}, radians(1 * 90.0));
		planeNode->position({planeNode->position().x, 0, planeNode->position().z});

		auto planePhysicsBody = PhysicsBody::StaticBody();
		planePhysicsBody->friction(1);
		planePhysicsBody->restitution(0.25);
		planeNode->physicsBody(std::move(planePhysicsBody));

		scene->rootNode()->addChild(planeNode);




		// add the palm tree

		//auto palmNode = Node::MeshNode(utils::MeshNamed("palm/palm"));
		auto palmNode = Node::MeshNode(utils::MeshNamed("cartoon_palm_tree/cartoon_palm_tree"));
		g_palmNode = palmNode.get();
		auto palmPhysicsBody = PhysicsBody::StaticBody();
		palmPhysicsBody->mass(0);
		palmPhysicsBody->friction(1);
		palmPhysicsBody->restitution(0.25);
		palmNode->physicsBody(std::move(palmPhysicsBody));
		scene->rootNode()->addChild(palmNode);

//		auto palmNode = Node::MeshNode(utils::MeshNamed("teapot/teapot"));
//		palmNode->scale({10, 10, 10});
//		g_palmNode = palmNode.get();
//		auto palmPhysicsBody = PhysicsBody::StaticBody();
//		palmPhysicsBody->mass(0);
//		palmPhysicsBody->friction(1);
//		palmPhysicsBody->restitution(0.25);
//		palmNode->physicsBody(std::move(palmPhysicsBody));
//		scene->rootNode()->addChild(palmNode);


		// add the duck

		auto duckNode = Node::MeshNode(utils::MeshNamed("rubber_duck/rubber_duck"));
//		auto duckNode = Node::MeshNode(utils::MeshNamed("siamese/siamese"));
//		auto duckNode = Node::MeshNode(utils::MeshNamed("teapot/teapot"));
		g_duckNode = duckNode.get();
		duckNode->position({/*4.5*/0, 25, 0});





	//	// #0
	//	_duckNode->physicsBody(PhysicsBody::KinematicBody());
	//	_duckNode->physicsBody()->shape()->type(PhysicsShapeType::ConcavePolyhedron);
	////	_duckNode->physicsBody()->shape()->type(PhysicsShapeType::ConvexHull);
	//
	//	// #1
	////	_duckNode->physicsBody(PhysicsBody::KinematicBody());
	////	auto duckPhysicsShape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, _duckNode.get());
	////	_duckNode->physicsBody()->shape(duckPhysicsShape);
	//
	//	// #2
	////	_duckNode->physicsBody(PhysicsBody::KinematicBody());
	////	auto duckPhysicsShape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, _duckNode->mesh().get());
	////	_duckNode->physicsBody()->shape(duckPhysicsShape);
	//
		// #3
		auto duckPhysicsShape = make_shared<PhysicsShape>(PhysicsShapeType::ConcavePolyhedron, duckNode);
		duckNode->physicsBody(make_unique<PhysicsBody>(PhysicsBodyType::Kinematic, duckPhysicsShape));

	//	// #4
	////	auto duckPhysicsShape = make_shared<PhysicsShape>(PhysicsShapeType::ConcavePolyhedron, _duckNode->mesh().get());
	//	_duckNode->physicsBody(make_shared<PhysicsBody>(PhysicsBodyType::Kinematic, duckPhysicsShape));

		auto duckSpinnerNode = Node::NamedNode("duck spinner");
//		g_duckSpinnerNode = duckSpinnerNode.get();
		duckSpinnerNode->addChild(duckNode);
		scene->rootNode()->addChild(duckSpinnerNode);



		vector<tuple<shared_ptr<Mesh>, shared_ptr<PhysicsShape>, float>> duckFruit{};


		auto mesh = utils::MeshNamed("cherries_lod/cherries_lod");
		auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		duckFruit.push_back({mesh, shape, 0.05});

		mesh = utils::MeshNamed("orange_lod/orange_lod");
		shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		duckFruit.push_back({mesh, shape, 0.185});

		mesh = utils::MeshNamed("pear_lod/pear_lod");
		shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		duckFruit.push_back({mesh, shape, 0.24});

		mesh = utils::MeshNamed("apple_lod/apple_lod");
		shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		duckFruit.push_back({mesh, shape, 0.225});

		mesh = utils::MeshNamed("banana_lod/banana_lod");
		shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		duckFruit.push_back({mesh, shape, 0.14});

		mesh = utils::MeshNamed("pineapple_lod/pineapple_lod");
		shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		duckFruit.push_back({mesh, shape, 0.9});

		g_duckFruit = &duckFruit;


	////	// add the paddle
	////
	////	_paddleNode = Node::MeshNode(make_shared<Box>(.5, 5, 20));
	////	auto paddleProperty = make_shared<MaterialProperty>(Color::Red());
	////	auto paddleMaterial = make_shared<Material>(nullptr, paddleProperty, nullptr);
	////	_paddleNode->mesh()->addMaterial(paddleMaterial);
	////	_paddleNode->position({15 - .25, 2.5, 0});
	////	auto paddlePhysicsBody = PhysicsBody::KinematicBody();
	//////	paddlePhysicsBody->friction(100);
	////	paddlePhysicsBody->restitution(0.25);
	////	_paddleNode->physicsBody(paddlePhysicsBody);
	////	scene->rootNode()->addChild(_paddleNode);
	//
	//
		// add cardboard boxes

		AddCardboardBoxes(*scene);


	// box spotlight
//	auto boxesLight = Light::SpotLight();
//	boxesLight->innerAngle(glm::radians(2.5));
//	boxesLight->outerAngle(glm::radians(10.0));
//	boxesLight->featheringMode(SpotlightFeatheringMode::Soft);
//	auto boxesLightNode = Node::LightNode(boxesLight);
//	boxesLightNode->position({-8.5, 18, -8.5});
//	boxesLightNode->eulerAngles({-1.2527435, 0.47099817, 0});
//	scene->rootNode()->addChild(boxesLightNode);


		auto boxesLight = Light::SpotLight(Color::LightGray());
		boxesLight->innerAngle(radians(20.0));
		boxesLight->outerAngle(radians(25.0));
		boxesLight->quadraticAttenuation(0.035);
		boxesLight->featheringMode(SpotlightFeatheringMode::Soft);
		auto boxesLightNode = Node::LightNode(boxesLight);
		boxesLightNode->position({-6.4, 1.2, -2.5});
		boxesLightNode->orientation({0.0999, 0.1969, -0.0202, 0.9751});
		scene->rootNode()->addChild(boxesLightNode);


//	A3D_APP_LOG_I("*** SCENE EXTENT: {} ***",
//				  to_string(scene->rootNode()->extent()));

	//	A3D_A3D_APP_LOG_I("Graph:\n{}", StringFromTree(*scene->rootNode()));
	//	auto children = scene->rootNode()->children(true);
	//	A3D_A3D_APP_LOG_I("CHILDREN REC:");
	//	for (auto& child : children) {
	//		if (child == scene->rootNode()){
	//			A3D_A3D_APP_LOG_I("\troot");
	//		}
	//		else if (child->name()) {
	//			A3D_A3D_APP_LOG_I("\t{}", *child->name());
	//		}
	//		else {
	//			A3D_A3D_APP_LOG_I("\t{:p}", (void*)child.get());
	//		}
	//	}



//		auto camera = make_shared<PerspectiveCamera>();
//		auto cameraNode = Node::CameraNode(camera);
//		cameraNode->position(vec3{0, 30, 60});
//		cameraNode->eulerAngles(vec3{glm::radians(-20.f), 0, 0});
//		auto flashLight = Light::SpotLight();
//		flashLight->innerAngle(glm::radians(2.5f));
//		flashLight->outerAngle(glm::radians(12.5f));
//		flashLight->featheringMode(SpotlightFeatheringMode::Sharp);
//		cameraNode->light(flashLight);
//		scene->visualWorld()->pointOfView(cameraNode);

wr = new WanderRotate();

		window->center();
		window->open();

		do {
			scene->update();
		} while (window->isOpen());
	}
	catch (Exception& e) {
		A3D_APP_LOG_F("Exception: {}", e.what());
		return -1;
	}

	return 0;
}

/// Scene Callbacks ///

void UpdateCallback(Scene& scene, double time, double deltaTime) {
	A3D_APP_LOG_T("scene: {:p}, time: {}, deltaTime: {}", (void*)&scene, time, deltaTime);

	GLFWWindow* window = nullptr;
	if (scene.visualWorld()) {
		window = static_cast<GLFWWindow*>(scene.visualWorld()->renderContext());
	}

	// rotate the duck
	auto rotationDeg = deltaTime * radians(30.0); // 30deg/sec

//	if (g_duckNode) {
//		auto duckEuler = g_duckNode->eulerAngles();
//		g_duckNode->eulerAngles({0, duckEuler.yaw - (float)rotationDeg, 0});
////		g_duckNode->eulerAngles({duckEuler.pitch - (float)rotationDeg, 0, 0});
////		g_duckNode->eulerAngles({0, 0, duckEuler.roll - (float)rotationDeg});
//	}

	if (g_duckNode) {
		wr->update(*g_duckNode, deltaTime);
	}

	// get input

	auto im = static_cast<DesktopInputManager*>(scene.inputManager());

	auto mouseButtonsDown = im->mouseButtonsDown();
	auto mouseButtonsPressed = im->mouseButtonsPressed();
	auto keysDown = im->keysDown();
	auto keysPressed = im->keysPressed();
	auto cursorCaptured = true;
	if (window) {
		cursorCaptured = window->cursorCaptured();
	}

	// TEMPORARY for macOS mouse input testing
//	if (keysPressed.count(Key::Z)) {
//		A3D_APP_LOG_I("Trying to re-initialize mouse input.");
//		auto windowInputManager = static_cast<GlfwInputManager*>(scene.inputManager());
//		try {
//			windowInputManager->initMouseInput();
//		}
//		catch (Exception) {
//			A3D_APP_LOG_E("Nada");
//		}
//	}

	if (keysPressed.count(Key::Escape)) {
		window->close();
		A3D_APP_LOG_I("open? {}", window->isOpen() ? "ya" : "no");
	}

	if (keysPressed.count(Key::Slash)) {
		window->cursorCaptured(!(window->cursorCaptured()));
	}

	if (keysPressed.count(Key::Backslash)) {
		utils::SaveSnapshot(*window);
	}



	if (keysPressed.count(Key::One)) {
		g_duckNode->physicsBody()->shape()->type(PhysicsShapeType::BoundingBox);
	}

	if (keysPressed.count(Key::Two)) {
		g_duckNode->physicsBody()->shape()->type(PhysicsShapeType::ConvexHull);
	}

	if (keysPressed.count(Key::Three)) {
		g_duckNode->physicsBody()->shape()->type(PhysicsShapeType::ConcavePolyhedron);
	}



	if (keysPressed.count(Key::Five)) {
		g_duckNode->physicsBody()->mass(0);
	}

	if (keysPressed.count(Key::Six)) {
		g_duckNode->physicsBody()->mass(10);
	}

	if (keysPressed.count(Key::Seven)) {
		g_duckNode->physicsBody()->mass(100);
	}



	if (keysPressed.count(Key::Eight)) {
		// remove all CylinderPhysicsShape nodes
		for (const auto& node : scene.rootNode()->children(true)) {
			auto body = node->physicsBody();
			if (body) {
				auto cylinderShape = dynamic_pointer_cast<CylinderPhysicsShape>(body->shape());
				if (cylinderShape) {
					node->removeFromParent();
				}
			}
		}
	}

	if (keysPressed.count(Key::Nine)) {
		// remove all dynamic body nodes
		for (const auto& node : scene.rootNode()->children(true)) {
			auto body = node->physicsBody();
			if (body) {
				if (body->type() == PhysicsBodyType::Dynamic) {
					node->removeFromParent();
				}
			}
		}
	}

	if (keysPressed.count(Key::Apostrophe)) {
		if (auto pov = scene.visualWorld()->pointOfView().lock()) {
			auto pos = pov->worldPosition();
			auto orient = pov->worldOrientation();
			A3D_APP_LOG_I("\ncamera position: ({:.4f}, {:.4f}, {:.4f})\n"
						  "camera orientation: ({:.6f}, {:.6f}, {:.6f}, {:.6f})",
						  pos.x, pos.y, pos.x, orient.x, orient.y, orient.z, orient.w);
		}
	}

//		if (keysPressed.count(Key::T)) {
//			A3D_APP_LOG_I("TREE:\n{}", utils::StringFromTree(*(scene.rootNode())));
//		}

	// spawn duck fruit

	if (keysPressed.count(Key::GraveAccent)) {
		AddBoxes(scene);
	}

	if (keysDown.count(Key::Tab)) {
		SpawnDuckFruit(scene, *g_duckNode);
	}

	if (keysPressed.count(Key::L)) {
		if (auto cameraNode = scene.visualWorld()->pointOfView().lock()) {
			if (cameraNode->light()) {
				cameraNode->light(nullptr);
			}
			else {
				auto flashLight = Light::SpotLight();
				flashLight->innerAngle(radians(5.0f));
				flashLight->outerAngle(radians(7.5f));
				flashLight->featheringMode(SpotlightFeatheringMode::Sharp);
				flashLight->quadraticAttenuation(.001);
				cameraNode->light(flashLight);
			}
		}
	}

	if (keysPressed.count(Key::Q)) {
		SpawnAutogeneratedPrimitives(scene);
	}

	// if (keysPressed.count(Key::Z)) {
	// 	SpawnInvisiblePrimitives(scene);
	// }

	if (keysPressed.count(Key::M)) {
		SpawnChainMail(scene);
	}

	if (keysPressed.count(Key::O)) {
		SpawnRecursiveTestTree(scene);
	}

	if (keysPressed.count(Key::T)) {
		SpawnHACDTeapot(scene);
	}

	if (keysPressed.count(Key::H)) {
		// NOTE: once the window is hidden, the scene keeps running but you
		// no longer get key events from the window!
		window->hidden(!window->hidden());
	}


	if (scene.visualWorld() && cursorCaptured) {

		if (mouseButtonsPressed.count(MouseButton::One)) {
			if (auto pov = scene.visualWorld()->pointOfView().lock()) {
				ShootSlurm(scene,
						   pov->worldPosition(),
						   pov->worldForward());
			}
		}

		if (mouseButtonsDown.count(MouseButton::Two)) {
			if (auto pov = scene.visualWorld()->pointOfView().lock()) {
				ShootSlurm(scene,
						   pov->worldPosition(),
						   pov->worldForward());
			}
		}
	}

	if (keysPressed.count(Key::F)) {
		//Log::MainLog().flush();
		if (A3D_MASK_CONTAINS(scene.debugOptions(), DebugOptions::ShowWireframes)) {
			scene.debugOptions(A3D_MASK_REMOVE(scene.debugOptions(),
											   DebugOptions::ShowWireframes));
		}
		else {
			scene.debugOptions(A3D_MASK_ADD(scene.debugOptions(),
											DebugOptions::ShowWireframes));
		}
	}
	if (keysPressed.count(Key::B)) {
		if (A3D_MASK_CONTAINS(scene.debugOptions(), DebugOptions::ShowBoundingBoxes)) {
			scene.debugOptions(A3D_MASK_REMOVE(scene.debugOptions(),
											   DebugOptions::ShowBoundingBoxes));
		}
		else {
			scene.debugOptions(A3D_MASK_ADD(scene.debugOptions(),
											DebugOptions::ShowBoundingBoxes));
		}
	}
	if (keysPressed.count(Key::I)) {
		if (A3D_MASK_CONTAINS(scene.debugOptions(), DebugOptions::ShowStatsOverlay)) {
			scene.debugOptions(A3D_MASK_REMOVE(scene.debugOptions(),
											   DebugOptions::ShowStatsOverlay));
		}
		else {
			scene.debugOptions(A3D_MASK_ADD(scene.debugOptions(),
											DebugOptions::ShowStatsOverlay));
		}
	}
	if (keysPressed.count(Key::P)) {
		if (A3D_MASK_CONTAINS(scene.debugOptions(), DebugOptions::ShowPhysicsBoundingBoxes)) {
			scene.debugOptions(A3D_MASK_REMOVE(scene.debugOptions(),
											   DebugOptions::ShowPhysicsBoundingBoxes));
		}
		else {
			scene.debugOptions(A3D_MASK_ADD(scene.debugOptions(),
											DebugOptions::ShowPhysicsBoundingBoxes));
		}
	}
	if (keysPressed.count(Key::G)) {
		if (A3D_MASK_CONTAINS(scene.debugOptions(), DebugOptions::ShowPhysicsWireframes)) {
			scene.debugOptions(A3D_MASK_REMOVE(scene.debugOptions(),
											   DebugOptions::ShowPhysicsWireframes));
		}
		else {
			scene.debugOptions(A3D_MASK_ADD(scene.debugOptions(),
											DebugOptions::ShowPhysicsWireframes));
		}
	}
	if (keysPressed.count(Key::C)) {
		if (A3D_MASK_CONTAINS(scene.debugOptions(), DebugOptions::ShowPhysicsContactPoints)) {
			scene.debugOptions(A3D_MASK_REMOVE(scene.debugOptions(),
											   DebugOptions::ShowPhysicsContactPoints));
		}
		else {
			scene.debugOptions(A3D_MASK_ADD(scene.debugOptions(),
											DebugOptions::ShowPhysicsContactPoints));
		}
	}
	if (keysPressed.count(Key::N)) {
		if (A3D_MASK_CONTAINS(scene.debugOptions(), DebugOptions::ShowPhysicsNormals)) {
			scene.debugOptions(A3D_MASK_REMOVE(scene.debugOptions(),
											   DebugOptions::ShowPhysicsNormals));
		}
		else {
			scene.debugOptions(A3D_MASK_ADD(scene.debugOptions(),
											DebugOptions::ShowPhysicsNormals));
		}
	}

	if (keysPressed.count(Key::V)) {
//		static auto pov = scene.visualWorld()->pointOfView();
//		if (scene.visualWorld()->pointOfView().expired()) {
//			A3D_APP_LOG_D("Adding POV...");
//			scene.visualWorld()->pointOfView(pov);
//		}
//		else {
//			A3D_APP_LOG_D("Removing POV...");
//			scene.visualWorld()->pointOfView().reset();
//		}
		window->vSyncEnabled(!window->vSyncEnabled());
	}

	if (keysPressed.count(Key::R)) {
		if (!window->recordingGIF()) {
			utils::StartGIFRecording(*window, {320, 240}, 8);
		}
		else {
			utils::StopGIFRecording(*window);
		}
	}

	if (keysDown.count(Key::Z)) {
		this_thread::sleep_for(std::chrono::milliseconds(8));
	}

	if (keysPressed.count(Key::U)) {
//			for (auto &n: scene.rootNode()->children(true)) {
//				auto mesh = n->mesh();
//				if (mesh) {
//					auto physicsBody = n->physicsBody();
//					if (physicsBody && physicsBody->type() != PhysicsBodyType::Static) {
//						bool coin = utils::Uniform(0, 1) == 1;
//						if (coin) {
//							n->removeFromParent();
//						}
//					}
//				}
//			}

		AddRing(scene);
	}

	vec2 mouseScrollWheelDelta = im->mouseScrollWheelDelta();
	if (mouseScrollWheelDelta.y > 0) {

		auto newSpeed = std::clamp(scene.physicalWorld()->speed() + mouseScrollWheelDelta.y * 0.1,
								   0.1, 1.0);
		scene.physicalWorld()->speed((float)newSpeed);
	}

	if (cursorCaptured) {

		// mouselook

		vec2 mousePositionDelta = im->mousePositionDelta();

		if (auto pov = scene.visualWorld()->pointOfView().lock()) {

			// look

			vec3 camForward = pov->worldForward();
			vec3 camRight = pov->worldRight();
			vec3 camUp = pov->worldUp();

			static const float MOUSE_SPEED_SCALAR = .002;
			static const float MOUSE_SPEED = MOUSE_SENSITIVITY * MOUSE_SPEED_SCALAR;

			float deltaRotX = math::atan(MOUSE_SPEED * mousePositionDelta.x);
			float deltaRotY = math::atan(MOUSE_SPEED * mousePositionDelta.y);

			vec3 angles = pov->eulerAngles();
			pov->eulerAngles(vec3(angles.x + deltaRotY, angles.y - deltaRotX, 0));

			// move

			static float MOVE_SPEED = math::max(scene.extent());

			float moveMultiplier = 1.0;
			if (keysDown.count(Key::LeftControl)) {
				moveMultiplier = 2.0;
			}

			if (keysDown.count(Key::W) || mouseButtonsDown.count(MouseButton::Four)) {
				vec3 positionDelta = (float)deltaTime * MOVE_SPEED * moveMultiplier * camForward;
				pov->position(pov->position() + positionDelta);
			}
			else if (keysDown.count(Key::S)) {
				vec3 positionDelta = (float)deltaTime * MOVE_SPEED * moveMultiplier * -camForward;
				pov->position(pov->position() + positionDelta);
			}

			if (keysDown.count(Key::A)) {
				vec3 positionDelta = (float)deltaTime * MOVE_SPEED * moveMultiplier * -camRight;
				pov->position(pov->position() + positionDelta);
			}
			else if (keysDown.count(Key::D)) {
				vec3 positionDelta = (float)deltaTime * MOVE_SPEED * moveMultiplier * camRight;
				pov->position(pov->position() + positionDelta);
			}

			if (keysDown.count(Key::Space)) {
				float direction = 1;
				if (keysDown.count(Key::LeftShift)) {
					direction = -1;
				}
				vec3 positionDelta = (float)deltaTime * MOVE_SPEED * moveMultiplier * camUp;
				pov->position(pov->position() + positionDelta * direction);
			}
		}
	}
}

/// VisualWorld Callbacks ///

void WillRenderCallback(VisualWorld& world, double time, double deltaTime) {
	A3D_APP_LOG_T("world: {:p}, time: {}, deltaTime: {}", (void*)&world, time, deltaTime);
}

void DidRenderCallback(VisualWorld& world, double time, double deltaTime) {
	A3D_APP_LOG_T("world: {:p}, time: {}, deltaTime: {}", (void*)&world, time, deltaTime);
}

/// PhysicalWorld Callbacks ///

void DidSimulatePhysicsCallback(PhysicalWorld& world, double time, double deltaTime) {
	A3D_APP_LOG_T("world: {:p}, time: {}, deltaTime: {}", (void*)&world, time, deltaTime);
}

/// Static ///

void InitLog() {

	string executableName = *utils::ExecutableName();

	auto nativeSink = make_unique<StdOutLogSink>();
	auto fileSink = make_unique<FileLogSink>(*(utils::ExecutableDirectory())
											 / (executableName + string(".log")));
	auto sinks = vector<unique_ptr<LogSink>>();
	sinks.push_back(std::move(nativeSink));
	sinks.push_back(std::move(fileSink));

	Log appLog{executableName, std::move(sinks)};
	appLog.level(APP_LOG_LEVEL);
	Log::AppLog(std::move(appLog));
}

void LogBuildInfo() {

	auto buildInfo = BuildInfo::Info();
	auto version = buildInfo.version();
	A3D_APP_LOG_I("A3D version: {}.{}.{}",
		  version.major, version.minor, version.patch);
	A3D_APP_LOG_I("Build: {}", buildInfo.number());
	A3D_APP_LOG_I("Type: {}",
		  buildInfo.type() == BuildInfo::Type::Debug ? "Debug" : "Release");
	A3D_APP_LOG_I("Origin: {}",
		  buildInfo.origin() == BuildInfo::Origin::CI ? "CI" : "AdHoc");
}

void SpawnDuckFruit(Scene& scene, Node& duckNode) {

	static const float SPAWN_RATE = 10.0; // pieces/sec

	A3D_EVERY(utils::chrono::sec_f_to_ms(1.0f/SPAWN_RATE), [&] {

		auto duckFruit = (*g_duckFruit)[uniform_linear(0, 5)];

		shared_ptr<Node> node = Node::MeshNode(get<0>(duckFruit));
		shared_ptr<PhysicsShape> physShape = get<1>(duckFruit);
		float mass = get<2>(duckFruit);

		// add local offset to duck, then convert that position to world space,
		// then attach to root node (below)
		node->transform(duckNode.worldTransform() * translate(mat4(1.0), vec3(0.0, 3.25, 0.2)));

		auto phyBody = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, physShape);
		phyBody->mass(mass);
		phyBody->restitution(0.25);
		phyBody->friction(1.0);

		// fruit starting orientation
		float heading = uniform_linear(0.0f, two_pi());
		float pitch = uniform_linear(0.0f, two_pi());
		float roll = uniform_linear(0.0f, two_pi());
		node->eulerAngles({heading, pitch, roll});

		// fruit linear velocity

		float lvX = uniform_n11() * 2.0f;
		float lvY = uniform_linear(1.0f, 10.0f);
		float lvZ = uniform_n11() * 2.0f;
		auto direction = duckNode.worldOrientation() * vec3{lvX, lvY, lvZ};
		phyBody->linearVelocity(direction);

		// fruit spin
		const float ANGULAR_VARIANCE = radians(60.0); // deg/sec
		phyBody->angularVelocity({ uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
								   uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
								   uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE) });

		node->physicsBody(std::move(phyBody));

		scene.rootNode()->addChild(node);
	});
}

// OG
//void ShootSlurm(Scene& scene, const vec3& location, const vec3& direction) {
//
//	const float SHOOT_RATE = 20; // cans/sec
//
//	A3D_EVERY(utils::chrono::sec_f_to_ms(1.0f/SHOOT_RATE), [&] {
//
//		static auto mesh = utils::MeshNamed("slurm/slurm");
//		mesh->materials()[0]->emission(mesh->materials()[0]->diffuse());
//		mesh->materials()[1]->emission(mesh->materials()[1]->diffuse());
//
//		auto node = Node::MeshNode(mesh);
//
//		node->position(location);
//
//		//static auto extent = node->mesh()->worldExtent(node->worldTransform());
//		static auto extent = node->mesh()->localExtent();
//		static auto physicsShape = make_shared<CylinderPhysicsShape>(extent.x/2.0, extent.y);
//		auto physicsBody = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, physicsShape);
//		physicsBody->mass(.354); // 12fl oz water @ 70F
//
//		physicsBody->restitution(1.0);
//		physicsBody->friction(0.35);
//		physicsBody->rollingFriction(0.05);
//
//		static auto light = Light::PointLight();
//		light->quadraticAttenuation(0.04);
//		node->light(light);
//
//		// add random factor
//
//		node->eulerAngles({ uniform_linear(0.0f, two_pi()),
//							uniform_linear(0.0f, two_pi()),
//							uniform_linear(0.0f, two_pi()) });
//
//		static const float ANGULAR_VARIANCE = radians(260.0); // deg/sec
//		physicsBody->angularVelocity({ uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
//									   uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
//									   uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE) });
//
//		const float VELOCITY = uniform_linear(40.0f, 60.0f);
//		static const float DIRECTION_VARIATION = 0.01;
//		const vec3 variedDirection = normalize(direction + uniform_ball(DIRECTION_VARIATION));
//		physicsBody->linearVelocity(variedDirection * VELOCITY);
//
//		node->physicsBody(std::move(physicsBody));
//
//		scene.rootNode()->addChild(node);
//	});
//}

// this is super fudgecycle
shared_ptr<Node> Hula(float minorRadius, float majorRadius) {

	static auto ringPhysicsNode = Node::NamedNode("Ring physics shape node");

	static const float CAPSULE_RADIUS = .1;
	static const float TORUS_MID_RADIUS = majorRadius - (majorRadius - minorRadius); // ! cap len??
	static const float CAPSULE_HEIGHT = (math::two_pi() * TORUS_MID_RADIUS) / 8.0f;
	static const auto visualMesh = Capsule::Mesh(CAPSULE_RADIUS,
												 CAPSULE_HEIGHT,
												 16, 16, 16);

	for (int s = 0; s < 8; ++s) {

		float angle = (float)(math::two_pi() / 8.0) * (float)s;

		auto partNode = Node::NamedNode("Ring capsule part node " + to_string(s + 1));
		partNode->mesh(visualMesh);

		quat rotation = quaternion(vec3(0, 0, 1), angle);
		mat4 rotMatrix = mat4_cast(rotation);
		mat4 translation = translate(mat4(1.0f), vec3(1.6, 0, 0)); // ! RADIUS
		mat4 transform = rotMatrix * translation;
		partNode->transform(transform);

		//partNode->hidden(true);

		ringPhysicsNode->addChild(partNode);
	}

	static const auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, ringPhysicsNode);

	auto torusMesh = Torus::Mesh(minorRadius + (minorRadius / 32.0f),
								 majorRadius+(majorRadius/32.0f), 128, 128);
	auto ringVisualNode = Node::MeshNode(torusMesh);

	auto colorProperty = Color::LightGray();
	auto colorMaterial = make_shared<Material>(monostate{}, colorProperty, monostate{});
	torusMesh->addMaterial(colorMaterial);

	auto body = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
	body->momentOfInertia({0, 0, 0});
	//body->affectedByGravity(false);
	ringVisualNode->physicsBody(std::move(body));

//	ringVisualNode->position({0, 1, 0});

//	scene.rootNode()->addChild(ringVisualNode);
	return ringVisualNode;
}


// Hula
void ShootSlurm(Scene& scene, const vec3& location, const vec3& direction) {

	const float SHOOT_RATE = 20; // cans/sec

	A3D_EVERY(utils::chrono::sec_f_to_ms(1.0f/SHOOT_RATE), [&] {

//		static auto mesh = utils::MeshNamed("slurm/slurm");
//		mesh->materials()[0]->emission(mesh->materials()[0]->diffuse());
//		mesh->materials()[1]->emission(mesh->materials()[1]->diffuse());
//
//		auto node = Node::MeshNode(mesh);
//
//		node->position(location);
//
//		//static auto extent = node->mesh()->worldExtent(node->worldTransform());
//		static auto extent = node->mesh()->localExtent();
//		static auto physicsShape = make_shared<CylinderPhysicsShape>(extent.x/2.0, extent.y);
//		auto physicsBody = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, physicsShape);
//		physicsBody->mass(.354); // 12fl oz water @ 70F
//
//		physicsBody->restitution(1.0);
//		physicsBody->friction(0.35);
//		physicsBody->rollingFriction(0.05);

		auto node = Hula(1.5, 1.6);

		node->position(location);

//		static auto light = Light::PointLight();
//		light->quadraticAttenuation(0.04);
//		node->light(light);

		// add random factor

		node->eulerAngles({ uniform_linear(0.0f, two_pi()),
							uniform_linear(0.0f, two_pi()),
							uniform_linear(0.0f, two_pi()) });

		static const float ANGULAR_VARIANCE = radians(260.0); // deg/sec
		node->physicsBody()->angularVelocity({ uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
									   uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE),
									   uniform_linear(-ANGULAR_VARIANCE, ANGULAR_VARIANCE) });

		const float VELOCITY = uniform_linear(40.0f, 60.0f);
		static const float DIRECTION_VARIATION = 0.01;
		const vec3 variedDirection = normalize(direction + uniform_ball(DIRECTION_VARIATION));
		node->physicsBody()->linearVelocity(variedDirection * VELOCITY);

		//node->physicsBody(std::move(physicsBody));

		scene.rootNode()->addChild(node);
	});
}

void AddBox(Scene& scene, const vec3& location, shared_ptr<Color> color) {

	auto node = Node::MeshNode(Box::Mesh(1.0, 1.0, 1.0));
	auto material = make_shared<Material>(monostate{}, monostate{}, monostate{}, color);
	node->mesh()->addMaterial(material);
	node->position(location);

	auto light = Light::PointLight(color);
	light->quadraticAttenuation(0.04);
	node->light(light);

	auto physicsBody = PhysicsBody::DynamicBody();
	physicsBody->mass(1.0);
	physicsBody->restitution(0.1);
	physicsBody->friction(0.25);

	static auto physicsShape = make_shared<PhysicsShape>(PhysicsShapeType::BoundingBox,
														 node->mesh());
	physicsBody->shape(physicsShape);

	node->physicsBody(std::move(physicsBody));

	scene.rootNode()->addChild(node);
}

void AddCardboardBox(Scene& scene, const vec3& location, const vec3& axis, float angle) {

	static auto mesh = utils::MeshNamed("cardboard_box/cardboard_box");

	auto node = Node::MeshNode(mesh);

	node->position(location);
	node->rotation(axis, angle);

	auto physicsBody = PhysicsBody::DynamicBody();
	static auto phyicsShape = make_shared<PhysicsShape>(PhysicsShapeType::BoundingBox, node->mesh());
	physicsBody->shape(phyicsShape);

	physicsBody->mass(0.1);
	physicsBody->restitution(0.1);
	physicsBody->friction(0.5);
	node->physicsBody(std::move(physicsBody));

	scene.rootNode()->addChild(node);
}

void SpawnHACDTeapot(Scene& scene) {

	auto teapotNode = Node::MeshNode(utils::MeshNamed("teapot/teapot"));

	ConvexDecomposer::Options options;
	options.maxConvexHulls = options.maxConvexHulls / 2;
	options.resolution = options.resolution / 2;
	options.maxRecursionDepth = options.maxRecursionDepth / 2;
	options.maxNumVerticesPerHull = options.maxNumVerticesPerHull / 2;

	auto decomposedElements = vector<unique_ptr<MeshElement>>();

	for (auto& element : teapotNode->mesh()->elements()) {
		auto decomposer = ConvexDecomposer(*element, options);
		auto elements = decomposer.decompose();

		decomposedElements.insert(decomposedElements.end(),
								  make_move_iterator(elements.begin()),
								  make_move_iterator(elements.end()));
	}

	auto decomposedTeapotMaterials = vector<shared_ptr<Material>>();
	decomposedTeapotMaterials.reserve(decomposedElements.size());
	for (int m=0; m<decomposedElements.size(); ++m) {
		auto randomColorProperty = Color::Random();
		decomposedTeapotMaterials.push_back(make_shared<Material>(monostate{},
																  monostate{},
																  monostate{},
																  randomColorProperty));
	}

	auto hacdTeapotMesh = make_shared<Mesh>(decomposedElements, decomposedTeapotMaterials);
	auto decomposedTeapotNode = Node::MeshNode(hacdTeapotMesh);
	decomposedTeapotNode->scale(decomposedTeapotNode->scale() * 20.0f);
	decomposedTeapotNode->position({0, 10, 0});
	scene.rootNode()->addChild(decomposedTeapotNode);
}

void AddBoxes(Scene& scene) {

	// 16 items
	static const int OBJECT_ARRAY_SIZE_X = 2;
	static const int OBJECT_ARRAY_SIZE_Y = 4;
	static const int OBJECT_ARRAY_SIZE_Z = 2;
	static const float X_OFFSET = -10.0;
	static const float Z_OFFSET = 10.0;

	int SPACING = 1.0;
	int DROP_HEIGHT = 40.0;
	int colorIndex = 0;
	for (int k=0; k<OBJECT_ARRAY_SIZE_Y; ++k) {
		for (int i=0;i <OBJECT_ARRAY_SIZE_X; ++i) {
			for(int j = 0; j<OBJECT_ARRAY_SIZE_Z; ++j) {
				vec3 position = vec3( SPACING * i - (OBJECT_ARRAY_SIZE_X / 2.0) + X_OFFSET,
									  DROP_HEIGHT + SPACING * k - (OBJECT_ARRAY_SIZE_Y / 2.0),
									  SPACING * j  - (OBJECT_ARRAY_SIZE_Z / 2.0) + Z_OFFSET );
				AddBox(scene, position, Color::Random());
			}
		}
	}
}

void AddCardboardBoxes(Scene& scene) {

	constexpr int HEIGHT = 7;

	static const vec3 AXIS = {0, 1, 0};
	static const float ANGLE = radians(25.0);

	static const float X_BASE = -15.0;
	static const float Y_BASE = 0.5;
	static const float Z_BASE = -10.0;

	static const float X_OFFSET = 0.75;
	static const float Y_OFFSET = 1.5;
	static const float Z_OFFSET = -0.36;

	for (int r=0; r<HEIGHT; ++r) {
		float x = X_BASE + (X_OFFSET * r);
		float y = Y_BASE + (Y_OFFSET * r);
		float z = Z_BASE + (Z_OFFSET * r);

		for (int i=0; i<HEIGHT-r; ++i) {
			AddCardboardBox(scene, {x, y, z}, AXIS, ANGLE);
			x += 1.5; z -= 0.75;
		}
	}
}

void AddRing(Scene& scene) {

	auto node = Node::NamedNode("Torus Node");
	static auto mesh = Torus::Mesh(.75, 1.0, 16, 16);
	static auto physicsShape = make_shared<PhysicsShape>(PhysicsShapeType::ConcavePolyhedron,
														 mesh);
	//auto physicsBody = PhysicsBody::DynamicBody();
	auto physicsBody = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, physicsShape);
	node->mesh(mesh);
	static auto materialProperty = Color::Yellow();
	static auto material = make_shared<Material>(monostate{}, materialProperty, monostate{});
	node->mesh()->addMaterial(material);
	node->physicsBody(std::move(physicsBody));
	node->position({0, 15, 0});
	scene.rootNode()->addChild(node);
}

shared_ptr<Node> ColoredSphereNode(shared_ptr<Color> color, string name) {

	auto sphereMesh = Sphere::Mesh(.25, 8);

	auto colorMaterial = make_shared<Material>(monostate{}, color, monostate{});

	sphereMesh->addMaterial(colorMaterial);

	auto node = Node::MeshNode(sphereMesh);
	node->name(name);

	return node;
}

void SpawnRecursiveTestTree(Scene& scene) {

	/*
	Node "a" [Shape]
	- Mesh [White]

		Node "b" [x: 5]
		- Mesh [Green]

			Node "c" [x: 5]
			- Mesh [Blue]

				Node "d" [x: 5]
				- Mesh [Yellow]

		Node "e" [y: 5]
		- Mesh [Orange]

			Node "f" [y: 5]
			- Mesh [Purple]

				Node "g" [y: 5]
				- Mesh [Lime]

		Node "h" [z: -5]
		- Mesh [Magenta]

			Node "i" [z: -5]
			- Mesh [Cyan]

				Node "j" [z: -5]
				- Mesh [Teal] */

	auto a = ColoredSphereNode(Color::White(), "a");
	auto b = ColoredSphereNode(Color::Green(), "b");
	auto c = ColoredSphereNode(Color::Blue(), "c");
	auto d = ColoredSphereNode(Color::Yellow(), "d");
	auto e = ColoredSphereNode(Color::Orange(), "e");
	auto f = ColoredSphereNode(Color::Purple(), "f");
	auto g = ColoredSphereNode(Color::Lime(), "g");
	auto h = ColoredSphereNode(Color::Magenta(), "h");
	auto i = ColoredSphereNode(Color::Cyan(), "i");
	auto j = ColoredSphereNode(Color::Teal(), "j");

	a->addChild(b);
	b->addChild(c);
	c->addChild(d);

	a->addChild(e);
	e->addChild(f);
	f->addChild(g);

	a->addChild(h);
	h->addChild(i);
	i->addChild(j);

	a->position({0, 15, 0});

	b->position({5, 0, 0});
	c->position({5, 0, 0});
	d->position({5, 0, 0});

	e->position({0, 5, 0});
	f->position({0, 5, 0});
	g->position({0, 5, 0});

	h->position({0, 0, -5});
	i->position({0, 0, -5});
	j->position({0, 0, -5});

	auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, a);
	auto physicsBody = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
	a->physicsBody(std::move(physicsBody));

	scene.rootNode()->addChild(a);
}

void SpawnAutogeneratedPrimitives(Scene& scene) {

	{ // box
		auto mesh = Box::Mesh(1, 1, 1);
		auto node = Node::MeshNode(mesh);
		auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		auto body = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
		node->physicsBody(std::move(body));
		node->position({5, 0, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // capsule
		auto mesh = Capsule::Mesh(.5, 2, 8, 8, 8);
		auto node = Node::MeshNode(mesh);
		auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		auto body = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
		node->physicsBody(std::move(body));
		node->position({0, 5, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // cone
		auto mesh = Cone::Mesh(1, 1, 8, 8);
		auto node = Node::MeshNode(mesh);
		auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		auto body = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
		node->physicsBody(std::move(body));
		node->position({0, 0, -5});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // cylinder
		auto mesh = Cylinder::Mesh(.5, 1, 8, 8);
		auto node = Node::MeshNode(mesh);
		auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		auto body = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
		node->physicsBody(std::move(body));
		node->position({-5, 0, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // plane
		auto mesh = Plane::Mesh(1, 1);
		auto node = Node::MeshNode(mesh);
		auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		auto body = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
		node->physicsBody(std::move(body));
		node->position({0, -5, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // sphere
		auto mesh = Sphere::Mesh(1, 8);
		auto node = Node::MeshNode(mesh);
		auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, mesh);
		auto body = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
		node->physicsBody(std::move(body));
		node->position({0, 0, 5});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}
}

void SpawnInvisiblePrimitives(Scene& scene) {

//	{ // box
//		auto node = Node::NamedNode("Box physics shape node");
//		auto shape = make_shared<BoxPhysicsShape>(1, 1, 1);
//		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
//		node->physicsBody(body);
//		node->position({5, 0, 0});
//		node->position({node->position().x, node->position().y+10, node->position().y});
//
//		scene.rootNode()->addChild(node);
//	}
//
//	{ // capsule
//
//		auto node = Node::NamedNode("Capsule physics shape node");
//		auto shape = make_shared<CapsulePhysicsShape>(.5, 2);
//		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
//		node->physicsBody(body);
//		node->position({0, 5, 0});
//		node->position({node->position().x, node->position().y+10, node->position().y});
//
//		scene.rootNode()->addChild(node);
//	}
//
//	{ // cone
//		auto node = Node::NamedNode("Cone physics shape node");
//		auto shape = make_shared<ConePhysicsShape>(1, 1);
//		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
//		node->physicsBody(body);
//		node->position({0, 0, -5});
//		node->position({node->position().x, node->position().y+10, node->position().y});
//
//		scene.rootNode()->addChild(node);
//	}
//
//	{ // cylinder
//		auto node = Node::NamedNode("Cylinder physics shape node");
//		auto shape = make_shared<CylinderPhysicsShape>(.5, 1);
//		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
//		node->physicsBody(body);
//		node->position({-5, 0, 0});
//		node->position({node->position().x, node->position().y+10, node->position().y});
//
//		scene.rootNode()->addChild(node);
//	}
//
//	{ // plane
//		auto node = Node::NamedNode("Plane physics shape node");
//		auto shape = make_shared<PlanePhysicsShape>(1, 1);
//		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
//		node->physicsBody(body);
//		node->position({0, -5, 0});
//		node->position({node->position().x, node->position().y+10, node->position().y});
//
//		scene.rootNode()->addChild(node);
//	}

	{ // sphere
		auto node = Node::NamedNode("Sphere physics shape node");
		auto shape = make_shared<SpherePhysicsShape>(1);
		auto body = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
		node->physicsBody(std::move(body));
		node->position({0, 0, 5});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);

//		testNode = node;
	}
}

//shared_ptr<CapsulePhysicsShape> ChainCapsule(float rotationRad) {
//
//}

//void SpawnChainMail(Scene& scene) {
//
//	static const float TORUS_MINOR_RADIUS = .9;
//	static const float TORUS_MAJOR_RADIUS = 1;
//
//	static bool once = false;
//	if (!once) {
//		once = true;
//
//		static const float TWO_PI = 2 * 3.14159265358;
//
//
////	scene.rootNode()->addChild(PhysicsChainElement(TORUS_MINOR_RADIUS,
////												   TORUS_MAJOR_RADIUS));
//
//		auto ringPhysicsNode = Node::NamedNode("Ring physics shape node");
//		//auto ringVisualNode =
//
//		static const float CAPSULE_RADIUS = .1;
////	static const float CAPSULE_HEIGHT = (TWO_PI * 1) / 8;
//		static const float TORUS_MID_RADIUS = TORUS_MAJOR_RADIUS - (TORUS_MAJOR_RADIUS - TORUS_MINOR_RADIUS);
//		static const float CAPSULE_HEIGHT = (TWO_PI * TORUS_MID_RADIUS) / 8.0;
////	static auto partShape = make_shared<CapsulePhysicsShape>(CAPSULE_RADIUS,
////															 CAPSULE_HEIGHT);
//		static auto visualMesh = make_shared<Capsule>(CAPSULE_RADIUS,
//													 CAPSULE_HEIGHT,
//													 16, 16, 16);
//
//		for (int s = 0; s < 8; ++s) {
//
//			float angle = (TWO_PI / 8.0) * (float) s;
//
//			auto partNode = Node::NamedNode("Ring capsule part node " + to_string(s + 1));
//			partNode->mesh(visualMesh);
//
//			quat rotation = angleAxis(angle, vec3(0, 0, 1));
//			mat4 rotMatrix = mat4_cast(rotation);
//			mat4 translation = translate(mat4(1.0f), vec3(1, 0, 0));
//			mat4 transform = rotMatrix * translation;
//			partNode->transform(transform);
//
//			partNode->hidden(true);
//
//			ringPhysicsNode->addChild(partNode);
//		}
//
//		auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, ringPhysicsNode);
//		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
//		//body->affectedByGravity(false);
//		ringPhysicsNode->physicsBody(body);
//
//		ringPhysicsNode->position({0, 1, 0});
//
////	auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
////	body->affectedByGravity(false);
////	node->physicsBody(body);
////	node->position({0, 5, 0});
//
//		scene.rootNode()->addChild(ringPhysicsNode);
//	}
//	else {
//		auto ringPhysicsNode = scene.rootNode()->child("Ring physics shape node", true);
//
//		auto mesh = make_shared<Torus>(TORUS_MINOR_RADIUS+(TORUS_MINOR_RADIUS/32.0),
//										   TORUS_MAJOR_RADIUS+(TORUS_MAJOR_RADIUS/32.0), 128, 128);
//		auto ringVisualNode = Node::MeshNode(mesh);
//
//		ringPhysicsNode->addChild(ringVisualNode);
//	}
//}

shared_ptr<Node> ChainmailLink(float minorRadius, float majorRadius) {

	static auto ringPhysicsNode = Node::NamedNode("Ring physics shape node");

	static const float CAPSULE_RADIUS = .1;
	static const float TORUS_MID_RADIUS = majorRadius - (majorRadius - minorRadius);
	static const float CAPSULE_HEIGHT = (math::two_pi() * TORUS_MID_RADIUS) / 8.0f;
	static const auto visualMesh = Capsule::Mesh(CAPSULE_RADIUS,
												 CAPSULE_HEIGHT,
												 16, 16, 16);

	for (int s = 0; s < 8; ++s) {

		float angle = (float)(math::two_pi() / 8.0) * (float)s;

		auto partNode = Node::NamedNode("Ring capsule part node " + to_string(s + 1));
		partNode->mesh(visualMesh);

		quat rotation = quaternion(vec3(0, 0, 1), angle);
		mat4 rotMatrix = mat4_cast(rotation);
		mat4 translation = translate(mat4(1.0f), vec3(1, 0, 0));
		mat4 transform = rotMatrix * translation;
		partNode->transform(transform);

		//partNode->hidden(true);

		ringPhysicsNode->addChild(partNode);
	}

	static const auto shape = make_shared<PhysicsShape>(PhysicsShapeType::ConvexHull, ringPhysicsNode);

	auto torusMesh = Torus::Mesh(minorRadius + (minorRadius / 32.0f),
								 majorRadius+(majorRadius/32.0f), 128, 128);
	auto ringVisualNode = Node::MeshNode(torusMesh);

	auto colorProperty = Color::LightGray();
	auto colorMaterial = make_shared<Material>(monostate{}, colorProperty, monostate{});
	torusMesh->addMaterial(colorMaterial);

	auto body = make_unique<PhysicsBody>(PhysicsBodyType::Dynamic, shape);
	//body->affectedByGravity(false);
	ringVisualNode->physicsBody(std::move(body));

	ringVisualNode->position({0, 1, 0});

//	scene.rootNode()->addChild(ringVisualNode);
	return ringVisualNode;
}

void SpawnChainMail(Scene& scene) {

	static const float PI = 3.14159265358;

	static const float TORUS_MINOR_RADIUS = .9;
	static const float TORUS_MAJOR_RADIUS = 1;

	// lavareef
	static const int CHAINMAIL_WIDTH = 3;
	static const int CHAINMAIL_HEIGHT = 4;

	// mushroomhill
//	static const int CHAINMAIL_WIDTH = 6;
//	static const int CHAINMAIL_HEIGHT = 8;

	static const int GROUND_OFFSET = 35;

//	for (int w=0; w<CHAINMAIL_WIDTH; ++w) {
//		for (int h=0; h<CHAINMAIL_HEIGHT; ++h) {
//			auto link = ChainmailLink(TORUS_MINOR_RADIUS, TORUS_MAJOR_RADIUS);
//			link->rotation({1, 0, 0}, (float) (w % 2 == 0 ? (PI / 6.0) : (-PI / 6.0)));
//			link->position({(3. * (2 * TORUS_MINOR_RADIUS) / 3.0) * w,
//							10 + (3. * (2 * TORUS_MINOR_RADIUS) / 3.0) * h,
//							0});
//			scene.rootNode()->addChild(link);
//		}
//	}

	auto chainmailNode = Node::NamedNode("chainmail");

	// horizontal chain
	for (int w=0; w<CHAINMAIL_WIDTH; ++w) {
		for (int h=0; h<CHAINMAIL_HEIGHT; ++h) {
			auto link = ChainmailLink(TORUS_MINOR_RADIUS, TORUS_MAJOR_RADIUS);
//		link->rotation({1, 0, 0}, (float) (w % 2 == 0 ? (PI / 6.0) : (-PI / 6.0)));
//			link->rotation({1, 0, 0}, PI / 6.0);
			float rotation = PI/12.0;
			float wStagger = 0;
			if (h%2 == 0) {
				rotation = -PI/12.0;
				wStagger = TORUS_MAJOR_RADIUS * 1.15f;
			}
			link->rotation({1, 0, 0}, rotation);
			//link->rotation({1, 0, 0}, (float)(h%2 == 0 ? (PI/6.0) : (-PI/6.0)));
			//auto stagger = (w%2 == 0 ? 0 : TORUS_MAJOR_RADIUS);
			auto stagger = 0;
			link->position(vec3(( ( ((2 * TORUS_MAJOR_RADIUS) * 1.15) * w) + wStagger),
					/*GROUND_OFFSET*/0 + ((1 * TORUS_MAJOR_RADIUS) * 1.15) * h,
								0));
			chainmailNode->addChild(link);
			//scene.rootNode()->addChild(link);
		}
	}

	chainmailNode->rotation({1, 0, 0}, pi_over_2());
//	chainmailNode->position({-chainmailNode->extent().x/2.0 + TORUS_MAJOR_RADIUS,
//							 GROUND_OFFSET,
//							 -chainmailNode->extent().y/2.0 + TORUS_MAJOR_RADIUS});
	chainmailNode->position({-chainmailNode->extent().x/2.0f + 1.0f,
							 GROUND_OFFSET,
							 -chainmailNode->extent().z/2.0f + 1.0f});
	scene.rootNode()->addChild(chainmailNode);

//	auto link = ChainmailLink(TORUS_MINOR_RADIUS, TORUS_MAJOR_RADIUS);
//	scene.rootNode()->addChild(link);

//	static const float TORUS_MINOR_RADIUS = .9;
//	static const float TORUS_MAJOR_RADIUS = 1;
//
//	static const float TWO_PI = 2 * 3.14159265358;
//
//	static auto ringPhysicsNode = Node::NamedNode("Ring physics shape node");
//
//	static const float CAPSULE_RADIUS = .1;
//	static const float TORUS_MID_RADIUS = TORUS_MAJOR_RADIUS - (TORUS_MAJOR_RADIUS - TORUS_MINOR_RADIUS);
//	static const float CAPSULE_HEIGHT = (TWO_PI * TORUS_MID_RADIUS) / 8.0;
//	static auto visualMesh = make_shared<Capsule>(CAPSULE_RADIUS,
//												 CAPSULE_HEIGHT,
//												 16, 16, 16);
//
//	for (int s = 0; s < 8; ++s) {
//
//		float angle = (TWO_PI / 8.0) * (float) s;
//
//		auto partNode = Node::NamedNode("Ring capsule part node " + to_string(s + 1));
//		partNode->mesh(visualMesh);
//
//		quat rotation = angleAxis(angle, vec3(0, 0, 1));
//		mat4 rotMatrix = mat4_cast(rotation);
//		mat4 translation = translate(mat4(1.0f), vec3(1, 0, 0));
//		mat4 transform = rotMatrix * translation;
//		partNode->transform(transform);
//
//		//partNode->hidden(true);
//
//		ringPhysicsNode->addChild(partNode);
//	}
//
//	auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, ringPhysicsNode);
//
//	auto torusMesh = make_shared<Torus>(TORUS_MINOR_RADIUS+(TORUS_MINOR_RADIUS/32.0),
//											TORUS_MAJOR_RADIUS+(TORUS_MAJOR_RADIUS/32.0), 128, 128);
//	auto ringVisualNode = Node::MeshNode(torusMesh);
//
//	auto colorProperty = make_shared<MaterialProperty>(Color::LightGray());
//	auto colorMaterial = make_shared<Material>(nullptr, colorProperty, nullptr);
//	torusMesh->addMaterial(colorMaterial);
//
//	auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
//	//body->affectedByGravity(false);
//	ringVisualNode->physicsBody(body);
//
//	ringVisualNode->position({0, 1, 0});
//
//	scene.rootNode()->addChild(ringVisualNode);
}


//{
//// orientation indicator
//static auto shaftElement = make_shared<Cylinder>(.1, 1, 16, 16)->elements().front();
//static auto coneElement = make_shared<Cone>(.5, .25, 16, 16)->elements().front();
//
//auto redMaterialProperty = MaterialProperty::ColorProperty(Color::Red());
//auto xShaftMesh = make_shared<Mesh>(shaftElement);
//
////	auto xArrowNode = Node::NamedNode("x arrow node");
////	xArrowNode->addChildren({Node::MeshNode(shaftMesh), Node::MeshNode(coneMesh)});
////	auto yArrowNode = Node::NamedNode("y arrow node");
////	yArrowNode->addChildren({Node::MeshNode(shaftMesh), Node::MeshNode(coneMesh)});
////	auto zArrowNode = Node::NamedNode("z arrow node");
////	zArrowNode->addChildren({Node::MeshNode(shaftMesh), Node::MeshNode(coneMesh)});
////	auto orientationNode = Node::NamedNode("Orientation indicator node");
////	orientationNode->addChildren({xArrowNode, yArrowNode, zArrowNode});
////	scene->rootNode()->addChild(orientationNode);
//}
