//
//  Example.cc
//	avara-engine
//
//  Created by Morgan Davis on 1/27/18.
//  Copyright © 2018 Morgan K Davis. All rights reserved.
//

#include "Example.h"

#include <iostream>

#include <glm/glm.hpp>

//#include "physics/ConvexDecomposer.h" // TEMPORARY
#include "utilities/Utilities.h"


using namespace ae;
using namespace ae::utils;
using namespace example;
using namespace glm;
using namespace std;
using namespace std::placeholders;


constexpr bool					USE_HIGH_DPI =			true;
constexpr unsigned				WINDOW_WIDTH =			1280;
constexpr unsigned				WINDOW_HEIGHT =			768;
constexpr bool					FULLSCREEN =			false;
constexpr ANTIALIASING_MODE		MSAA_MODE =				ANTIALIASING_MODE::MSAA_4X;
constexpr bool					ENABLE_VSYNC =			false;
constexpr bool					CAPTURE_CURSOR =		false;
constexpr float					MOUSE_SENSITIVITY =		0.5;
constexpr float					PHYSICS_TIMESTEP =		1.0/120.0;

constexpr bool					DARK =					false;

/***************************************************************************************
	Static Prototypes
 ***************************************************************************************/

static shared_ptr<Node> SpawnDuckFruit(Scene& scene, shared_ptr<Node> duckNode);
static shared_ptr<Node> AddSlurm(Scene& scene, const vec3& location, const vec3& axis, float angle);
static shared_ptr<Node> ShootBall(Scene& scene, const vec3& location, const vec3& direction);
static shared_ptr<Node> AddBox(Scene& scene, const vec3& location, shared_ptr<Color> color);
static shared_ptr<Node> AddCardboardBox(Scene& scene, const vec3& location, const vec3& axis, float angle);
//static void SpawnHACDTeapot(Scene& scene);
static void AddBoxes(Scene& scene);
static void AddCardboardBoxes(Scene& scene);
static void AddSlurms(Scene& scene);
static void AddRing(Scene& scene);
static shared_ptr<Node> ColoredSphereNode(shared_ptr<Color> color, string name);
static void SpawnRecursiveTestTree(Scene& scene);
static void SpawnAutogeneratedPrimitives(Scene& scene);
static void SpawnInvisiblePrimitives(Scene& scene);
static shared_ptr<Node> ChainmailLink(float radius, float height);
static void SpawnChainMail(Scene& scene);

/***************************************************************************************
	Public
 ***************************************************************************************/

int Example::run(const vector<string>& args) {

	//AE_INIT();

	_logger = make_shared<Logger>("example", Logger::MainLogger()->sinks());
	LOG_I(_logger, "");



	//Logger::MainLogger()->f4("this {} a {} string {}", "is", "crufty", 69);
	//AE_LOG_F("this {} a {} string {}", "is", "crufty", 69);
	//Logger::MainLogger()->f4("this {} a {} string {}", "is", "crufty", 69);


	auto window = make_shared<Window>(RENDER_API::OPENGL,
									  FULLSCREEN,
									  WINDOW_WIDTH,
									  WINDOW_HEIGHT,
									  USE_HIGH_DPI,
									  MSAA_MODE);
	window->vSyncEnabled(ENABLE_VSYNC);
	window->cursorCaptured(CAPTURE_CURSOR);

	auto visualWorld = make_shared<VisualWorld>(window);
	visualWorld->fogStartDistance(50.0);
	visualWorld->fogEndDistance(400.0);
	visualWorld->fogDensityExponent(1.0);
	visualWorld->fogColor(DARK ? Color::DarkGray() : Color::LightGray());
	auto background = DARK
					  ? make_shared<MaterialProperty>(Color::Black())
					  : make_shared<MaterialProperty>(CubeImageNamed("stormy", "png"));
	visualWorld->background(background);
	visualWorld->willRender(bind(&Example::willRenderCallback, this, _1, _2));
	visualWorld->didRender(bind(&Example::didRenderCallback, this, _1, _2));

	auto physicalWorld = make_shared<PhysicalWorld>();
	physicalWorld->timestep(PHYSICS_TIMESTEP);
	physicalWorld->didSimulate(bind(&Example::didSimulatePhysicsCallback, this, _1, _2));

	auto inputManager = make_shared<WindowInputManager>(window);

	auto scene = make_shared<Scene>(visualWorld, physicalWorld, inputManager);
	scene->debugOptions(DEBUG_OPTIONS::SHOW_STATS_OVERLAY);
	scene->update(bind(&Example::updateCallback, this, _1, _2));

	auto ambientColor = DARK
						? Color::LightGray()
						: make_shared<Color>(233, 218, 185); // sunset
	auto ambientLight = make_shared<Light>(LIGHT_TYPE::AMBIENT, ambientColor);
	auto ambientLightNode = Node::LightNode(ambientLight);
	scene->rootNode()->addChild(ambientLightNode);

	auto pointColor = DARK
					  ? Color::LightGray()
					  : make_shared<Color>((uint32_t)0x3F2A00FF); // dark orangish
	auto pointLight = make_shared<Light>(LIGHT_TYPE::POINT, pointColor);
	pointLight->attenuationFactor(0.0);
	auto pointLightNode = Node::LightNode(pointLight);
	pointLightNode->position(vec3(35, 20, (DARK ? 1.0 : -1.0 ) * 35) * vec3(2.5, 2.5, 2.5));
	scene->rootNode()->addChild(pointLightNode);


	// box
//	const float BOX_DIM = 10.0;
//	auto boxNode = make_shared<Node>("Box node");
//	boxNode->geometry(make_shared<Box>(BOX_DIM, BOX_DIM, BOX_DIM));
//	auto boxImage = ImageNamed("grid10");
//	//auto gridImage = ImageNamed("grid10_512");
//	auto boxMaterialProperty = make_shared<MaterialProperty>(boxImage);
//	boxMaterialProperty->wrapS(WRAP_MODE::REPEAT);
//	boxMaterialProperty->wrapT(WRAP_MODE::REPEAT);
//	boxMaterialProperty->maxAnisotropy(16);
//	boxMaterialProperty->minificationFilter(FILTER_MODE::LINEAR_MIPMAP_LINEAR);
//	boxMaterialProperty->magnificationFilter(FILTER_MODE::LINEAR);
//	auto boxMaterial = make_shared<Material>(nullptr, boxMaterialProperty, nullptr);
//	boxMaterial->uvScale(BOX_DIM/10.0);
//	boxMaterial->doubleSided(true);
//	boxNode->geometry()->addMaterial(boxMaterial);
//	boxNode->position({-20, 0, 20});
//
//	auto boxPhysicsBody = PhysicsBody::StaticBody();
//	boxPhysicsBody->mass(0);
//	boxPhysicsBody->friction(1);
//	boxPhysicsBody->restitution(0.25);
//	boxNode->physicsBody(boxPhysicsBody);
//
//	scene->rootNode()->addChild(boxNode);


	// ground plane

	const float PLANE_LENGTH = 50.0;
	const float PLANE_WIDTH = 50.0;
	auto planeNode = make_shared<Node>("Ground plane node");
		planeNode->geometry(make_shared<Box>(PLANE_LENGTH, PLANE_WIDTH, 0));
	auto gridImage = DARK ? ImageNamed("grid10")->inverted() : ImageNamed("grid10");
	auto planeMaterialProperty = make_shared<MaterialProperty>(gridImage);
	planeMaterialProperty->wrapS(WRAP_MODE::REPEAT);
	planeMaterialProperty->wrapT(WRAP_MODE::REPEAT);
	planeMaterialProperty->maxAnisotropy(16);
	planeMaterialProperty->minificationFilter(FILTER_MODE::LINEAR_MIPMAP_LINEAR);
	planeMaterialProperty->magnificationFilter(FILTER_MODE::LINEAR);
	shared_ptr<Material> planeMaterial = nullptr;
	if (DARK) {
		planeMaterial = make_shared<Material>(nullptr,
											  nullptr,
											  nullptr,
											  planeMaterialProperty);
	}
	else {
		planeMaterial = make_shared<Material>(nullptr,
											  planeMaterialProperty,
											  make_shared<MaterialProperty>(Color::Gray()));
	}

	planeMaterial->uvScale(PLANE_LENGTH/10.0);
	planeMaterial->doubleSided(false);
	planeNode->geometry()->addMaterial(planeMaterial);
	planeNode->rotation({1, 0, 0}, radians(3*90.0));
	planeNode->position({planeNode->position().x, 0, planeNode->position().z});

	auto planePhysicsBody = PhysicsBody::StaticBody();
	planeNode->physicsBody(planePhysicsBody);
	planePhysicsBody->mass(0);
	planePhysicsBody->friction(1);
	planePhysicsBody->restitution(0.25);

	scene->rootNode()->addChild(planeNode);


	// add the palm tree

	auto palmScene = SceneNamed("palm2/palm2", "obj");
	_palmNode = palmScene->rootNode();
	_palmNode->name("Palm node");
	for (auto n : palmScene->rootNode()->children(true)) {
		if (n->geometry()) {
			for (auto m : n->geometry()->materials()) {
				m->doubleSided(true);
			}
		}
	}

	auto palmPhysicsBody = PhysicsBody::StaticBody();
	palmPhysicsBody->mass(0);
	palmPhysicsBody->friction(1);
	palmPhysicsBody->restitution(0.25);
	_palmNode->physicsBody(palmPhysicsBody);

	scene->rootNode()->addChild(palmScene->rootNode());


	// add the duck

	_duckNode = SceneNamed("rubberDuck/rubberDuck", "obj")->rootNode()->childNamed("g duck", false);
	AE_LOG_I("DUCK NODE: {}", StringFromTree(*_duckNode));
	_duckNode->position({/*4.5*/0, 15, 0});


	// #0
	_duckNode->physicsBody(PhysicsBody::KinematicBody());
	_duckNode->physicsBody()->shape()->type(PHYSICS_SHAPE_TYPE::CONCAVE_POLYHEDRON);
//	_duckNode->physicsBody()->shape()->type(PHYSICS_SHAPE_TYPE::CONVEX_HULL);

	// #1
//	_duckNode->physicsBody(PhysicsBody::KinematicBody());
//	auto duckPhysicsShape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, _duckNode);
//	_duckNode->physicsBody()->shape(duckPhysicsShape);

	// #2
//	_duckNode->physicsBody(PhysicsBody::KinematicBody());
//	auto duckPhysicsShape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, _duckNode->geometry());
//	_duckNode->physicsBody()->shape(duckPhysicsShape);

	// #3
//	auto duckPhysicsShape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONCAVE_POLYHEDRON, _duckNode);
//	_duckNode->physicsBody(make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::KINEMATIC, duckPhysicsShape));

	// #4
//	auto duckPhysicsShape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONCAVE_POLYHEDRON, _duckNode->geometry());
//	_duckNode->physicsBody(make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::KINEMATIC, duckPhysicsShape));

	_duckSpinnerNode = make_shared<Node>("duck spinner");
	_duckSpinnerNode->addChild(_duckNode);
	scene->rootNode()->addChild(_duckSpinnerNode);



//	// add the paddle
//
//	_paddleNode = Node::GeometryNode(make_shared<Box>(.5, 5, 20));
//	auto paddleProperty = make_shared<MaterialProperty>(Color::Red());
//	auto paddleMaterial = make_shared<Material>(nullptr, paddleProperty, nullptr);
//	_paddleNode->geometry()->addMaterial(paddleMaterial);
//	_paddleNode->position({15 - .25, 2.5, 0});
//	auto paddlePhysicsBody = PhysicsBody::KinematicBody();
////	paddlePhysicsBody->friction(100);
//	paddlePhysicsBody->restitution(0.25);
//	_paddleNode->physicsBody(paddlePhysicsBody);
//	scene->rootNode()->addChild(_paddleNode);
//
//
//	// add cardboard boxes
//	AddCardboardBoxes(*scene);
//
//	// add slurms
//	AddSlurms(*scene);



	LOG_I(_logger, "*** SCENE EXTENT: {} ***", StringFromGLMVec3(scene->rootNode()->extent()));

//	AE_LOG_I("Graph:\n{}", StringFromTree(*scene->rootNode()));
//	auto children = scene->rootNode()->children(true);
//	AE_LOG_I("CHILDREN REC:");
//	for (auto& child : children) {
//		if (child == scene->rootNode()){
//			AE_LOG_I("\troot");
//		}
//		else if (child->name().has_value()) {
//			AE_LOG_I("\t{}", *child->name());
//		}
//		else {
//			AE_LOG_I("\t{:p}", (void*)child.get());
//		}
//	}

	window->open();
	scene->run();
	
	return 0;
}

/***************************************************************************************
	Scene Callbacks
 ***************************************************************************************/

void Example::updateCallback(Scene& scene, float time) {
	LOG_T(_logger, "scene: {:p}, time: {}", (void*)&scene, time);

	static float previousSeconds = time;
	float deltaSeconds = time - previousSeconds;
	previousSeconds = time;

	auto inputManager = scene.inputManager();

	//shared_ptr<RenderContext> renderContext = nullptr;
	shared_ptr<Window> window = nullptr;
	if (scene.visualWorld()) {
		//renderContext = scene.visualWorld()->renderContext();
		window = static_pointer_cast<Window>(scene.visualWorld()->renderContext());
	}

	// rotate the duck
	float rotationDeg = deltaSeconds * radians(30.0); // 30deg/sec

	if (_duckSpinnerNode) {
		//auto duckRotation = _duckSpinnerNode->rotation();
		//_duckSpinnerNode->rotation({0, 1, 0, duckRotation.w + rotationDeg});
		auto duckSpinnerEuler = _duckSpinnerNode->eulerAngles();
		_duckSpinnerNode->eulerAngles({0, duckSpinnerEuler.y - rotationDeg, 0});
	}

//	for (auto& c : scene.rootNode()->children(true)) {
//		if (c->geometry()) {
//			if (dynamic_pointer_cast<Cylinder>(c->geometry())) {
//				AE_LOG_I("{}", utils::StringFromGLMVec3(c->worldPosition()));
//			}
//		}
//	}

	// get input
	
	auto mouseButtonsDown = inputManager->mouseButtonsDown();
	auto mouseButtonsPressed = inputManager->mouseButtonsPressed();
	auto keysDown = inputManager->keysDown();
	auto keysPressed = inputManager->keysPressed();
	auto cursorCaptured = true;
	if (window) {
		cursorCaptured = window->cursorCaptured();
	}

	
	if (keysPressed.count(KEY::ESCAPE)) {
		window->close();
	}

	if (keysPressed.count(KEY::FORWARD_DELETE)) {
		scene.paused(!scene.paused());
	}

	if (keysPressed.count(KEY::SLASH)) {
		window->cursorCaptured(!(window->cursorCaptured()));
	}

	if (keysPressed.count(KEY::BACKSLASH)) {
		SaveSnapshot(*window);
	}

	if (keysPressed.count(KEY::ONE)) {
		_duckNode->physicsBody()->shape()->type(PHYSICS_SHAPE_TYPE::BOUNDING_BOX);
	}

	if (keysPressed.count(KEY::TWO)) {
		_duckNode->physicsBody()->shape()->type(PHYSICS_SHAPE_TYPE::CONVEX_HULL);
	}

	if (keysPressed.count(KEY::THREE)) {
		_duckNode->physicsBody()->shape()->type(PHYSICS_SHAPE_TYPE::CONCAVE_POLYHEDRON);
	}

	if (!scene.paused()) {

		if (keysPressed.count(KEY::T)) {
			LOG_I(_logger, "TREE:\n{}", StringFromTree(*(scene.rootNode())));
		}

		// spawn duck fruit

		if (keysPressed.count(KEY::GRAVE_ACCENT)) {
			AddBoxes(scene);
		}

		if (keysDown.count(KEY::TAB)) {
			auto fruitNode = SpawnDuckFruit(scene, _duckNode);
			if (!_fruit1Node) {
				_fruit1Node = fruitNode;
			}
		}

		if (keysPressed.count(KEY::L)) {
			AddRing(scene);
		}

		if (keysPressed.count(KEY::Q)) {
			SpawnAutogeneratedPrimitives(scene);
		}

		if (keysPressed.count(KEY::Z)) {
			SpawnInvisiblePrimitives(scene);
		}

		if (keysPressed.count(KEY::M)) {
			SpawnChainMail(scene);
		}

		if (keysPressed.count(KEY::O)) {
			SpawnRecursiveTestTree(scene);
		}

//		if (keysPressed.count(KEY::ONE)) {
//			scene.physicalWorld()->speed(0.1);
//		}
//
//		if (keysPressed.count(KEY::ZERO)) {
//			scene.physicalWorld()->speed(1.0);
//		}
//
//		if (keysPressed.count(KEY::TWO)) {
//			scene.physicalWorld()->speed(2.0);
//		}

		if (keysPressed.count(KEY::J)) {
			if (_fruit1Node) {
				_fruit1Node->physicsBody()->affectedByGravity(!(_fruit1Node->physicsBody()->affectedByGravity()));
			}
		}

//	if (keysPressed.count(KEY::H)) {
//		SpawnHACDTeapot(scene);
//	}

		// move paddle

		static const float PADDLE_SPEED = 5.0; // m/s
		if (keysDown.count(KEY::EQUAL)) {
			if (_paddleNode) {
				auto p = _paddleNode->position();
				_paddleNode->position({p.x + deltaSeconds * PADDLE_SPEED, p.y, p.z});
			}
		}
		if (keysDown.count(KEY::MINUS)) {
			if (_paddleNode) {
				auto p = _paddleNode->position();
				_paddleNode->position({p.x - deltaSeconds * PADDLE_SPEED, p.y, p.z});
			}
		}

		if (scene.visualWorld() && cursorCaptured) {
			if (mouseButtonsPressed.count(MOUSE_BUTTON::ONE)) {
				auto pov = scene.visualWorld()->pointOfView();
				ShootBall(scene,
						  pov->worldPosition(),
						  pov->worldForward());
			}

			if (mouseButtonsDown.count(MOUSE_BUTTON::TWO)) {
				auto pov = scene.visualWorld()->pointOfView();
				ShootBall(scene,
						  pov->worldPosition(),
						  pov->worldForward());
			}
		}

		if (keysPressed.count(KEY::F)) {
			if (DEBUG_OPTIONS_CONTAINS(scene.debugOptions(), DEBUG_OPTIONS::SHOW_WIREFRAMES)) {
				scene.debugOptions(DEBUG_OPTIONS_REMOVE(scene.debugOptions(),
														DEBUG_OPTIONS::SHOW_WIREFRAMES));
			} else {
				scene.debugOptions(DEBUG_OPTIONS_ADD(scene.debugOptions(),
													 DEBUG_OPTIONS::SHOW_WIREFRAMES));
			}
		}
		if (keysPressed.count(KEY::B)) {
			if (DEBUG_OPTIONS_CONTAINS(scene.debugOptions(), DEBUG_OPTIONS::SHOW_BOUNDING_BOXES)) {
				scene.debugOptions(DEBUG_OPTIONS_REMOVE(scene.debugOptions(),
														DEBUG_OPTIONS::SHOW_BOUNDING_BOXES));
			} else {
				scene.debugOptions(DEBUG_OPTIONS_ADD(scene.debugOptions(),
													 DEBUG_OPTIONS::SHOW_BOUNDING_BOXES));
			}
		}
		if (keysPressed.count(KEY::I)) {
			if (DEBUG_OPTIONS_CONTAINS(scene.debugOptions(), DEBUG_OPTIONS::SHOW_STATS_OVERLAY)) {
				scene.debugOptions(DEBUG_OPTIONS_REMOVE(scene.debugOptions(),
														DEBUG_OPTIONS::SHOW_STATS_OVERLAY));
			} else {
				scene.debugOptions(DEBUG_OPTIONS_ADD(scene.debugOptions(),
													 DEBUG_OPTIONS::SHOW_STATS_OVERLAY));
			}
		}
		if (keysPressed.count(KEY::P)) {
			if (DEBUG_OPTIONS_CONTAINS(scene.debugOptions(), DEBUG_OPTIONS::SHOW_PHYSICS_BOUNDING_BOXES)) {
				scene.debugOptions(DEBUG_OPTIONS_REMOVE(scene.debugOptions(),
														DEBUG_OPTIONS::SHOW_PHYSICS_BOUNDING_BOXES));
			} else {
				scene.debugOptions(DEBUG_OPTIONS_ADD(scene.debugOptions(),
													 DEBUG_OPTIONS::SHOW_PHYSICS_BOUNDING_BOXES));
			}
		}
		if (keysPressed.count(KEY::G)) {
			if (DEBUG_OPTIONS_CONTAINS(scene.debugOptions(), DEBUG_OPTIONS::SHOW_PHYSICS_WIREFRAMES)) {
				scene.debugOptions(DEBUG_OPTIONS_REMOVE(scene.debugOptions(),
														DEBUG_OPTIONS::SHOW_PHYSICS_WIREFRAMES));
			} else {
				scene.debugOptions(DEBUG_OPTIONS_ADD(scene.debugOptions(),
													 DEBUG_OPTIONS::SHOW_PHYSICS_WIREFRAMES));
			}
		}
		if (keysPressed.count(KEY::C)) {
			if (DEBUG_OPTIONS_CONTAINS(scene.debugOptions(), DEBUG_OPTIONS::SHOW_PHYSICS_CONTACT_POINTS)) {
				scene.debugOptions(DEBUG_OPTIONS_REMOVE(scene.debugOptions(),
														DEBUG_OPTIONS::SHOW_PHYSICS_CONTACT_POINTS));
			} else {
				scene.debugOptions(DEBUG_OPTIONS_ADD(scene.debugOptions(),
													 DEBUG_OPTIONS::SHOW_PHYSICS_CONTACT_POINTS));
			}
		}
		if (keysPressed.count(KEY::N)) {
			if (DEBUG_OPTIONS_CONTAINS(scene.debugOptions(), DEBUG_OPTIONS::SHOW_PHYSICS_NORMALS)) {
				scene.debugOptions(DEBUG_OPTIONS_REMOVE(scene.debugOptions(),
														DEBUG_OPTIONS::SHOW_PHYSICS_NORMALS));
			} else {
				scene.debugOptions(DEBUG_OPTIONS_ADD(scene.debugOptions(),
													 DEBUG_OPTIONS::SHOW_PHYSICS_NORMALS));
			}
		}

		if (keysPressed.count(KEY::V)) {
			window->vSyncEnabled(!window->vSyncEnabled());
		}

		if (keysPressed.count(KEY::R)) {
			if (!window->recordingGIF()) {
				StartGIFRecording(*window, 320, 8);
			} else {
				StopGIFRecording(*window);
			}
		}

		if (keysPressed.count(KEY::U)) {
			for (auto &n: scene.rootNode()->children(true)) {
				auto geometry = n->geometry();
				if (geometry) {
					auto physicsBody = n->physicsBody();
					if (physicsBody && physicsBody->type() != PHYSICS_BODY_TYPE::STATIC) {
						bool coin = Uniform(0, 1) == 1;
						if (coin) {
							n->removeFromParent();
						}
					}
				}
			}
		}

		vec2 mouseScrollWheelDelta = scene.inputManager()->mouseScrollWheelDelta();
		if (mouseScrollWheelDelta.y) {

			auto newSpeed = std::clamp(scene.physicalWorld()->speed() + mouseScrollWheelDelta.y * 0.1,
									   0.1, 1.0);
			scene.physicalWorld()->speed(newSpeed);
		}

		if (cursorCaptured) {

			// mouselook

			vec2 mousePositionDelta = inputManager->mousePositionDelta();

			auto pov = scene.visualWorld()->pointOfView();
			if (pov) {

				// look

				vec3 camForward = pov->worldForward();
				vec3 camRight = pov->worldRight();
				vec3 camUp = pov->worldUp();

				static const float MOUSE_SPEED_SCALAR = .002;
				static const float MOUSE_SPEED = MOUSE_SENSITIVITY * MOUSE_SPEED_SCALAR;

				float deltaRotX = atan(MOUSE_SPEED * mousePositionDelta.x);
				float deltaRotY = atan(MOUSE_SPEED * mousePositionDelta.y);

				vec3 angles = pov->eulerAngles();
				pov->eulerAngles(vec3(angles.x + deltaRotY, angles.y - deltaRotX, 0));

				// move

				static float MOVE_SPEED = Max(scene.rootNode()->extent());

				float moveMultiplier = 1.0;
				if (keysDown.count(KEY::LEFT_CONTROL)) {
					moveMultiplier = 2.0;
				}

				if (keysDown.count(KEY::W) || mouseButtonsDown.count(MOUSE_BUTTON::FOUR)) {
					vec3 positionDelta = deltaSeconds * MOVE_SPEED * moveMultiplier * camForward;
					pov->position(pov->position() + positionDelta);
				} else if (keysDown.count(KEY::S)) {
					vec3 positionDelta = deltaSeconds * MOVE_SPEED * moveMultiplier * -camForward;
					pov->position(pov->position() + positionDelta);
				}

				if (keysDown.count(KEY::A)) {
					vec3 positionDelta = deltaSeconds * MOVE_SPEED * moveMultiplier * -camRight;
					pov->position(pov->position() + positionDelta);
				} else if (keysDown.count(KEY::D)) {
					vec3 positionDelta = deltaSeconds * MOVE_SPEED * moveMultiplier * camRight;
					pov->position(pov->position() + positionDelta);
				}

				if (keysDown.count(KEY::SPACE)) {
					float direction = 1;
					if (keysDown.count(KEY::LEFT_SHIFT)) {
						direction = -1;
					}
					vec3 positionDelta = deltaSeconds * MOVE_SPEED * moveMultiplier * camUp;
					pov->position(pov->position() + positionDelta * direction);
				}
			}
		}
	}
}

/***************************************************************************************
	VisualWorld Callbacks
 ***************************************************************************************/

void Example::willRenderCallback(VisualWorld& world, float time) {
	LOG_T(_logger, "world: {:p}, time: {}", (void*)&world, time);
}

void Example::didRenderCallback(VisualWorld& world, float time) {
	LOG_T(_logger, "world: {:p}, time: {}", (void*)&world, time);
}

/***************************************************************************************
	PhysicalWorld Callbacks
 ***************************************************************************************/

void Example::didSimulatePhysicsCallback(PhysicalWorld& world, float time) {
	LOG_T(_logger, "world: {:p}, time: {}", (void*)&world, time);
}

/***************************************************************************************
	Static
 ***************************************************************************************/

shared_ptr<Node> SpawnDuckFruit(Scene& scene, shared_ptr<Node> duckNode) {
	
	constexpr float SPAWN_RATE = 7.5; // pieces/sec
	
	float time = scene.time();
	static float lastSSpawnTime = 0;
	if ((time - lastSSpawnTime) >= (1.0/SPAWN_RATE)) {

//		AddCardboardBox(scene, {0, 10, 0}, {1, 0, 0}, 0.0f);
//		lastSSpawnTime = time;
//		return nullptr;
		
		
		unsigned fruitNum = Uniform(0, 5);
		static shared_ptr<Node> node = nullptr;
		//shared_ptr<PhysicsShape> physicsShape = nullptr;
		float mass = 1;

		switch (fruitNum) {
			case 0: {
				AE_LOG_D("cherry");
				node = SceneNamed("cherry1_lod/cherry1_lod", "obj")->rootNode();
				mass = 0.05;
				break;
			}
			case 1: {
				AE_LOG_D("orange");
				node = SceneNamed("orange1_lod/orange1_lod", "obj")->rootNode();
				mass = 0.185;
				break;
			}
			case 2: {
				AE_LOG_D("pear");
				node = SceneNamed("pear_lod/pear_lod", "obj")->rootNode();
				mass = 0.24;
				break;
			}
			case 3: {
				AE_LOG_D("apple");
				node = SceneNamed("apple1_lod/apple1_lod", "obj")->rootNode();
				mass = 0.225;
				break;
			}
			case 4: {
				AE_LOG_D("banana");
				node = SceneNamed("banana_lod/banana_lod", "obj")->rootNode();
				mass = 0.14;
				break;
			}
			case 5: {
				node = SceneNamed("pineapple_lod/pinapple_lod", "obj")->rootNode();
				mass = 0.9;
				break;
			}
			default: return nullptr;
		}

//		node->scale({5.0, 5.0, 5.0});
		// add local offset to duck, then convert that position to world space,
		// then attach to root node (below)
		node->position(duckNode->worldPosition() + vec3(0.0, 2.5, 0.0));
		
		//	node->scale({3.0, 3.0, 3.0});
		//#warning TEMPORARY workaround for physics scaling
		//	for (auto& c : node->children(true)) {
		//		LOG_D(_logger, "c tr: {}", StringFromGLMMat4(c->transform()));
		//		c->geometry()->burnTransform(node->transform(), true);
		//		node->transform(mat4(1.0));
		//	}

		//auto physicsShape = PhysicsShape::ConvexHullShape();
		auto physicsBody = PhysicsBody::DynamicBody();
		//physicsBody->shape(physicsShape);


		// *** without this a compound body would be maade including 'sphereGeometry' below
		// this way we are telling AE to make the physics body based solely on this particular geometry
//		auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL,
//											   node->children(false).front()->geometry());
//		physicsBody->shape(shape);
		///////////////////



		physicsBody->mass(mass);
		physicsBody->restitution(0.25);
		physicsBody->friction(1);
		
		
		//physicsBody->angularDamping(0.1);
		//physicsBody->angularFactor({.1, .1, .1});
		
//		physicsBody->linearSleepingThreshold(0.1);
//		physicsBody->angularSleepingThreshold(.01);


		// add a visual-only child
//		auto sphereGeometry = make_shared<Sphere>(.5f, 16);
//		//auto sphereNode =
//		auto sphereNode = Node::GeometryNode(sphereGeometry);
//		sphereNode->position({1, 0, 0});
//		node->addChild(sphereNode);


		
		// add random factor

		static const float PI = 3.1415; // windows doesn't like M_PI from cmath (?)
		float heading = Uniform(0.0f, 2*PI);
		float pitch = Uniform(0.0f, 2*PI);
		float roll = Uniform(0.0f, 2*PI);

		node->eulerAngles({heading, pitch, roll});

		float linearVelocityX = Uniform(-2.0f, 2.0f);
		float linearVelocityY = Uniform(5.0f, 12.0f);	
		float linearVelocityZ = Uniform(-2.0f, 2.0f);
		
		physicsBody->linearVelocity({linearVelocityX, linearVelocityY, linearVelocityZ});
		
		constexpr float ANGULAR_VARIANCE = 45.0; // deg/sec
		float angularVelocityX = Uniform(radians(-ANGULAR_VARIANCE), radians(ANGULAR_VARIANCE));	
		float angularVelocityY = Uniform(radians(-ANGULAR_VARIANCE), radians(ANGULAR_VARIANCE));	
		float angularVelocityZ = Uniform(radians(-ANGULAR_VARIANCE), radians(ANGULAR_VARIANCE));	
		
		physicsBody->angularVelocity({angularVelocityX, angularVelocityY, angularVelocityZ});
		
		node->physicsBody(physicsBody);
		//node->physicsBody()->shape()->type(PHYSICS_SHAPE_TYPE::CONCAVE_POLYHEDRON);
		
		scene.rootNode()->addChild(node);
		
		lastSSpawnTime = time;
		
		return node;
	}
	
	return nullptr;
}

shared_ptr<Node> AddSlurm(Scene& scene, const vec3& location, const vec3& axis, float angle) {
	
	static auto fileScene = SceneNamed("slurm/slurm", "obj");
	static auto fileNode = fileScene->rootNode();
	static auto fileCanNode = fileNode->childNamed("g slurm", false);
	static auto fileMaterials = fileCanNode->geometry()->materials();
	
	auto canNode = Node::GeometryNode(fileCanNode->geometry());
	for (auto& m : fileMaterials) {
		canNode->geometry()->addMaterial(m);
	}

	//auto node = make_shared<Node>("Slurm");
	//node->addChild(canNode);
	auto node = canNode;

	node->position(location);
	node->rotation(axis, angle);
	auto physicsBody = PhysicsBody::DynamicBody();
	physicsBody->mass(.4);
	static auto physicsShape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, node.get());
	physicsBody->shape(physicsShape);
//	physicsBody->friction(5);
	node->physicsBody(physicsBody);
	scene.rootNode()->addChild(node);
	
	return node;
}

shared_ptr<Node> ShootBall(Scene& scene, const vec3& location, const vec3& direction) {

	constexpr float SHOOT_RATE = 20; // balls/sec

	float time = scene.time();
	static float lastShootTime = 0;
	if ((time - lastShootTime) >= (1.0/SHOOT_RATE)) {

//		static shared_ptr<Color> colors[] = {
//				Color::White(),
//				Color::Red(),
//				Color::Orange(),
//				Color::Yellow(),
//				Color::Lime(),
//				Color::Blue()
//		};
//		auto color = colors[Uniform(0, 5)];
//
//
//		constexpr float BALL_RADIUS = 0.55;
//		auto sphereGrometry = make_shared<Sphere>(BALL_RADIUS, 3);
//		auto node = Node::GeometryNode(sphereGrometry);
//		auto diffuseProperty = make_shared<MaterialProperty>(color);
//		auto specularProperty = make_shared<MaterialProperty>(Color::White());
//		auto material = make_shared<Material>(nullptr, diffuseProperty, specularProperty);
//		material->specularExponent(125.0);
//		node->geometry()->addMaterial(material);
//		node->position(location);
//
//
////		auto node = SceneNamed("beachball1/beachball1", "obj")->rootNode()->children(false)[0];
////		node->position(location);
//
//
//		auto physicsBody = PhysicsBody::DynamicBody();
//		physicsBody->mass(0.2); // vollyball
//		physicsBody->restitution(1.0);
//		physicsBody->friction(0.015);
//		physicsBody->rollingFriction(0.15);
////		physicsBody->friction(0);
////		physicsBody->rollingFriction(0);
//







		static auto fileScene = SceneNamed("slurm/slurm", "obj");
		static auto fileCanNode = fileScene->rootNode()->childNamed("g slurm", false);
		static auto fileMaterials = fileCanNode->geometry()->materials();

		// just copying the node?
		auto node = Node::GeometryNode(fileCanNode->geometry());
		for (auto& m : fileMaterials) {
			node->geometry()->addMaterial(m);
		}

		node->position(location);
//		static auto physicsShape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL,
//														   fileCanNode->geometry());
		static auto extent = node->extent();
		static auto physicsShape = make_shared<CylinderPhysicsShape>(extent.x/2.0, extent.y);
		auto physicsBody = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, physicsShape);
//		auto physicsBody = PhysicsBody::DynamicBody();
		physicsBody->mass(.354); // 12fl oz water 70F
//	physicsBody->friction(5);
///
		physicsBody->restitution(1.0);
		physicsBody->friction(0.35);
		physicsBody->rollingFriction(0.05);
		///
		//node->physicsBody(physicsBody);







		// add random factor

		static const float PI = 3.1415; // windows doesn't like M_PI from cmath (?)
		float heading = Uniform(0.0f, 2*PI);
		float pitch = Uniform(0.0f, 2*PI);
		float roll = Uniform(0.0f, 2*PI);

		node->eulerAngles({heading, pitch, roll});

//		float linearVelocityX = Uniform(-2.0f, 2.0f);
//		float linearVelocityY = Uniform(5.0f, 12.0f);
//		float linearVelocityZ = Uniform(-2.0f, 2.0f);
//
//		physicsBody->linearVelocity({linearVelocityX, linearVelocityY, linearVelocityZ});

		constexpr float ANGULAR_VARIANCE = 270.0; // deg/sec
		float angularVelocityX = Uniform(radians(-ANGULAR_VARIANCE), radians(ANGULAR_VARIANCE));
		float angularVelocityY = Uniform(radians(-ANGULAR_VARIANCE), radians(ANGULAR_VARIANCE));
		float angularVelocityZ = Uniform(radians(-ANGULAR_VARIANCE), radians(ANGULAR_VARIANCE));

		physicsBody->angularVelocity({angularVelocityX, angularVelocityY, angularVelocityZ});

		node->physicsBody(physicsBody);
		//node->physicsBody()->shape()->type(PHYSICS_SHAPE_TYPE::CONCAVE_POLYHEDRON);

		scene.rootNode()->addChild(node);




		constexpr float BALL_VELOCITY = 50.0;
		constexpr float DIRECTION_VARIATION = 0.015f;
		auto variedDirection = direction + vec3(Uniform(-DIRECTION_VARIATION, DIRECTION_VARIATION),
												Uniform(-DIRECTION_VARIATION, DIRECTION_VARIATION),
												Uniform(-DIRECTION_VARIATION, DIRECTION_VARIATION));
		physicsBody->linearVelocity(normalize(variedDirection) * BALL_VELOCITY);

//		physicsBody->linearVelocity(normalize(direction) * BALL_VELOCITY);

//		constexpr float velocityVariation = 0.05f;
//		physicsBody->linearVelocity(direction + vec3(Uniform(-velocityVariation, velocityVariation),
//													 Uniform(-velocityVariation, velocityVariation),
//													 Uniform(-velocityVariation, velocityVariation)));
//		constexpr float angularVelocityVariation = radians(15.0f); // deg/sec
//		physicsBody->angularVelocity(vec3(Uniform(-angularVelocityVariation, angularVelocityVariation),
//										  Uniform(-angularVelocityVariation, angularVelocityVariation),
//										  Uniform(-angularVelocityVariation, angularVelocityVariation)));

		node->physicsBody(physicsBody);

//		scene.rootNode()->addChild(node);

		lastShootTime = time;

		return node;
	}

	return nullptr;
}

//shared_ptr<Node> ShootBall(Scene& scene, const vec3& location, const vec3& direction) {
//
//	constexpr float SHOOT_RATE = 20; // balls/sec
//
//	float time = scene.renderContext().lock()->sceneTime();
//	static float lastShootTime = 0;
//	if ((time - lastShootTime) >= (1.0/SHOOT_RATE)) {
//
//		static shared_ptr<Color> colors[] = {
//			Color::White(),
//			Color::Red(),
//			Color::Orange(),
//			Color::Yellow(),
//			Color::Lime(),
//			Color::Blue()
//		};
//		auto color = colors[Uniform(0, 5)];
//
//
//		constexpr float BALL_RADIUS = 0.55;
//		auto sphereGrometry = make_shared<Sphere>(BALL_RADIUS, 3);
//		auto node = Node::GeometryNode(sphereGrometry);
//		auto diffuseProperty = make_shared<MaterialProperty>(color);
//		auto specularProperty = make_shared<MaterialProperty>(Color::White());
//		auto material = make_shared<Material>(nullptr, diffuseProperty, specularProperty);
//		material->specularExponent(125.0);
//		node->geometry()->addMaterial(material);
//		node->position(location);
//
//
////		auto node = SceneNamed("beachball1/beachball1", "obj")->rootNode()->children(false)[0];
////		node->position(location);
//
//
//		auto physicsBody = PhysicsBody::DynamicBody();
//		physicsBody->mass(0.2); // vollyball
//		physicsBody->restitution(1.0);
//		physicsBody->friction(0.015);
//		physicsBody->rollingFriction(0.15);
////		physicsBody->friction(0);
////		physicsBody->rollingFriction(0);
//
//		constexpr float BALL_VELOCITY = 45.0;
//		constexpr float DIRECTION_VARIATION = 0.035f;
//		auto variedDirection = direction + vec3(Uniform(-DIRECTION_VARIATION, DIRECTION_VARIATION),
//												Uniform(-DIRECTION_VARIATION, DIRECTION_VARIATION),
//												Uniform(-DIRECTION_VARIATION, DIRECTION_VARIATION));
//		physicsBody->linearVelocity(normalize(variedDirection) * BALL_VELOCITY);
//
////		physicsBody->linearVelocity(normalize(direction) * BALL_VELOCITY);
//
////		constexpr float velocityVariation = 0.05f;
////		physicsBody->linearVelocity(direction + vec3(Uniform(-velocityVariation, velocityVariation),
////													 Uniform(-velocityVariation, velocityVariation),
////													 Uniform(-velocityVariation, velocityVariation)));
////		constexpr float angularVelocityVariation = radians(15.0f); // deg/sec
////		physicsBody->angularVelocity(vec3(Uniform(-angularVelocityVariation, angularVelocityVariation),
////										  Uniform(-angularVelocityVariation, angularVelocityVariation),
////										  Uniform(-angularVelocityVariation, angularVelocityVariation)));
//
//		node->physicsBody(physicsBody);
//
//		scene.rootNode()->addChild(node);
//
//		lastShootTime = time;
//
//		return node;
//	}
//
//	return nullptr;
//}

shared_ptr<Node> AddBox(Scene& scene, const vec3& location, shared_ptr<Color> color) {
	
	auto node = Node::GeometryNode(make_shared<Box>(1.0, 1.0, 1.0));
	auto materialProperty = make_shared<MaterialProperty>(color);
	auto material = make_shared<Material>(nullptr, materialProperty, nullptr);
	node->geometry()->addMaterial(material);
	node->position(location);
	
	auto physicsBody = PhysicsBody::DynamicBody();
	physicsBody->mass(1.0);
	physicsBody->restitution(0.1);
	physicsBody->friction(0.25);

	static auto physicsShape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::BOUNDING_BOX,
														 node->geometry().get());
	physicsBody->shape(physicsShape);
	
	node->physicsBody(physicsBody);
	
	scene.rootNode()->addChild(node);
	
	return node;
}

shared_ptr<Node> AddCardboardBox(Scene& scene, const vec3& location, const vec3& axis, float angle) {
	
	static auto fileScene = SceneNamed("cardboardBox2/cardboardBox2", "obj");
	static auto fileNode = fileScene->rootNode();
	static auto fileTapeNode = fileNode->childNamed("g tape", false);
	static auto fileBoxNode = fileNode->childNamed("g box", false);
	
	auto tapeNode = Node::GeometryNode(fileTapeNode->geometry());
	tapeNode->geometry()->addMaterial(fileTapeNode->geometry()->firstMaterial());
	auto boxNode = Node::GeometryNode(fileBoxNode->geometry());
	boxNode->geometry()->addMaterial(fileBoxNode->geometry()->firstMaterial());
	
	auto node = make_shared<Node>("Cardboard box");
	node->addChild(tapeNode);
	node->addChild(boxNode);

	node->position(location);
	node->rotation(axis, angle);

	auto physicsBody = PhysicsBody::DynamicBody();
	static auto phyicsShape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::BOUNDING_BOX, boxNode->geometry().get());
	physicsBody->shape(phyicsShape);

 	// this SHOULD work but doesn't
//	auto physicsShape = PhysicsShape::BoundingBoxShape();
//	auto physicsBody = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, physicsShape);

	physicsBody->mass(0.1);
	physicsBody->restitution(0.1);
	physicsBody->friction(0.5);
	//physicsBody->angularFactor({2.0, 2.0, 2.0});
	node->physicsBody(physicsBody);
	
	scene.rootNode()->addChild(node);
	
	return node;
}

//void SpawnHACDTeapot(Scene& scene) {
//
//	auto teapotNode = SceneNamed("teapot", "dae")->rootNode()->child("teapot", false);
//
//	ConvexDecomposer::Options options;
//	options.maxConvexHulls = options.maxConvexHulls / 2;
//	options.resolution = options.resolution / 2;
//	options.maxRecursionDepth = options.maxRecursionDepth / 2;
//	options.maxNumVerticesPerHull = options.maxNumVerticesPerHull / 2;
//
//	auto decomposedElements = vector<shared_ptr<GeometryElement>>();
//
//	for (auto& element : teapotNode->geometry()->elements()) {
//		auto decomposer = ConvexDecomposer(element, options);
//		auto elements = decomposer.decompose();
//		decomposedElements.insert(decomposedElements.begin(),
//								  elements.begin(),
//								  elements.end());
//	}
//
//	auto decomposedTeapotMaterials = vector<shared_ptr<Material>>();
//	decomposedTeapotMaterials.reserve(decomposedElements.size());
//	for (int m=0; m<decomposedElements.size(); ++m) {
//		auto randomColorProperty = make_shared<MaterialProperty>(Color::Random());
//		decomposedTeapotMaterials.push_back(make_shared<Material>(nullptr,
//																  nullptr,
//																  nullptr,
//																  randomColorProperty));
//	}
//
//	auto hacdTeapotGeometry = make_shared<Geometry>(decomposedElements, decomposedTeapotMaterials);
//	auto decomposedTeapotNode = Node::GeometryNode(hacdTeapotGeometry);
//	decomposedTeapotNode->scale({.25, .25, .25});
//	decomposedTeapotNode->rotation({1, 0, 0}, radians(-90.0));
//	decomposedTeapotNode->position({0, 0, 4});
//	scene.rootNode()->addChild(decomposedTeapotNode);
//}

void AddBoxes(Scene& scene) {
	
	// 16 items
	constexpr unsigned OBJECT_ARRAY_SIZE_X = 2;
	constexpr unsigned OBJECT_ARRAY_SIZE_Y = 4;
	constexpr unsigned OBJECT_ARRAY_SIZE_Z = 2;
	constexpr float X_OFFSET = -10.0;
	constexpr float Z_OFFSET = 10.0;
	
	unsigned SPACING = 1.0;
	unsigned DROP_HEIGHT = 40.0;
	unsigned colorIndex = 0;
	for (int k=0; k<OBJECT_ARRAY_SIZE_Y; ++k) {
		for (int i=0;i <OBJECT_ARRAY_SIZE_X; ++i) {
			for(int j = 0; j<OBJECT_ARRAY_SIZE_Z; ++j) {
				auto color = Color::Random();
				vec3 position = { SPACING * i - (OBJECT_ARRAY_SIZE_X / 2.0) + X_OFFSET,
					DROP_HEIGHT + SPACING * k - (OBJECT_ARRAY_SIZE_Y / 2.0),
					SPACING * j  - (OBJECT_ARRAY_SIZE_Z / 2.0) + Z_OFFSET};
				AddBox(scene, position, color);
			}
		}
	}
}

void AddCardboardBoxes(Scene& scene) {
	
	constexpr unsigned HEIGHT = 7;
	
	static const vec3 AXIS = {0, 1, 0};
	static const float ANGLE = radians(25.0);
	
	constexpr float X_BASE = -15.0;
	constexpr float Y_BASE = 0.5;
	constexpr float Z_BASE = -10.0;
	
	constexpr float X_OFFSET = 0.75;
	constexpr float Y_OFFSET = 1.5;
	constexpr float Z_OFFSET = -0.36;
	
	for (unsigned r=0; r<HEIGHT; ++r) {
		float x = X_BASE + (X_OFFSET * r);
		float y = Y_BASE + (Y_OFFSET * r);
		float z = Z_BASE + (Z_OFFSET * r);
		
		for (unsigned i=0; i<HEIGHT-r; ++i) {
			AddCardboardBox(scene, {x, y, z}, AXIS, ANGLE);
			x += 1.5; z -= 0.75;
		}
	}
}

void AddSlurms(Scene& scene) {

	float x = 15 - .25;
	float y = 5.5;
	float z = -9;
	
	for (unsigned i=0; i<19; ++i) {
		AddSlurm(scene, {x, y, z}, {0, 1, 0}, radians((float)Uniform(0, 359)));
		z += 1;
	}
}

static void AddRing(Scene& scene) {

	auto node = Node::NamedNode("Torus Node");
	static auto geometry = make_shared<Torus>(.75, 1.0, 16, 16);
	static auto physicsShape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONCAVE_POLYHEDRON,
														 geometry.get());
	//auto physicsBody = PhysicsBody::DynamicBody();
	auto physicsBody = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, physicsShape);
	node->geometry(geometry);
	static auto materialProperty = make_shared<MaterialProperty>(Color::Yellow());
	static auto material = make_shared<Material>(nullptr, materialProperty, nullptr);
	node->geometry()->addMaterial(material);
	node->physicsBody(physicsBody);
	node->position({0, 15, 0});
	scene.rootNode()->addChild(node);
}

shared_ptr<Node> ColoredSphereNode(shared_ptr<Color> color, string name) {

	auto sphereGeometry = make_shared<Sphere>(.25, 8);

	auto colorProperty = make_shared<MaterialProperty>(color);
	auto colorMaterial = make_shared<Material>(nullptr, colorProperty, nullptr);

	sphereGeometry->addMaterial(colorMaterial);

	auto node = Node::GeometryNode(sphereGeometry);
	node->name(name);

	return node;
}

void SpawnRecursiveTestTree(Scene& scene) {

	/*
	Node "a" [Shape]
	- Geometry [White]

		Node "b" [x: 5]
		- Geometry [Green]

			Node "c" [x: 5]
			- Geometry [Blue]

				Node "d" [x: 5]
				- Geometry [Yellow]

		Node "e" [y: 5]
		- Geometry [Orange]

			Node "f" [y: 5]
			- Geometry [Purple]

				Node "g" [y: 5]
				- Geometry [Lime]

		Node "h" [z: -5]
		- Geometry [Magenta]

			Node "i" [z: -5]
			- Geometry [Cyan]

				Node "j" [z: -5]
				- Geometry [Teal] */

	auto a = ColoredSphereNode(Color::White(), "a");
	auto b = ColoredSphereNode(Color::Green(), "b");
	auto c = ColoredSphereNode(Color::Blue(), "c");
	auto d = ColoredSphereNode(Color::Yellow(), "d");
	auto e = ColoredSphereNode(Color::Orange(), "e");
	auto f = ColoredSphereNode(Color::Purple(), "f");
	auto g = ColoredSphereNode(Color::Lime(), "g");
	auto h = ColoredSphereNode(Color::Magenta(), "h");
	auto i = ColoredSphereNode(Color::Cyan(), "i");
	auto j = ColoredSphereNode(Color::Teal(), "j");

	a->addChild(b);
	b->addChild(c);
	c->addChild(d);

	a->addChild(e);
	e->addChild(f);
	f->addChild(g);

	a->addChild(h);
	h->addChild(i);
	i->addChild(j);

	a->position({0, 15, 0});

	b->position({5, 0, 0});
	c->position({5, 0, 0});
	d->position({5, 0, 0});

	e->position({0, 5, 0});
	f->position({0, 5, 0});
	g->position({0, 5, 0});

	h->position({0, 0, -5});
	i->position({0, 0, -5});
	j->position({0, 0, -5});

	auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, a.get());
	auto physicsBody = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
	a->physicsBody(physicsBody);

	scene.rootNode()->addChild(a);
}

void SpawnAutogeneratedPrimitives(Scene& scene) {

	{ // box
		auto geometry = make_shared<Box>(1, 1, 1);
		auto node = Node::GeometryNode(geometry);
		auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, geometry.get());
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({5, 0, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // capsule
		auto geometry = make_shared<Capsule>(.5, 2, 8, 8, 8);
		auto node = Node::GeometryNode(geometry);
		auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, geometry.get());
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({0, 5, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // cone
		auto geometry = make_shared<Cone>(1, 1, 8, 8);
		auto node = Node::GeometryNode(geometry);
		auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, geometry.get());
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({0, 0, -5});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // cylinder
		auto geometry = make_shared<Cylinder>(.5, 1, 8, 8);
		auto node = Node::GeometryNode(geometry);
		auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, geometry.get());
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({-5, 0, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // plane
		auto geometry = make_shared<Plane>(1, 1);
		auto node = Node::GeometryNode(geometry);
		auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, geometry.get());
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({0, -5, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // sphere
		auto geometry = make_shared<Sphere>(1, 8);
		auto node = Node::GeometryNode(geometry);
		auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, geometry.get());
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({0, 0, 5});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}
}

void SpawnInvisiblePrimitives(Scene& scene) {

	{ // box
		auto node = Node::NamedNode("Box physics shape node");
		auto shape = make_shared<BoxPhysicsShape>(1, 1, 1);
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({5, 0, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // capsule
		auto node = Node::NamedNode("Capsule physics shape node");
		auto shape = make_shared<CapsulePhysicsShape>(.5, 2);
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({0, 5, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // cone
		auto node = Node::NamedNode("Cone physics shape node");
		auto shape = make_shared<ConePhysicsShape>(1, 1);
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({0, 0, -5});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // cylinder
		auto node = Node::NamedNode("Cylinder physics shape node");
		auto shape = make_shared<CylinderPhysicsShape>(.5, 1);
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({-5, 0, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // plane
		auto node = Node::NamedNode("Plane physics shape node");
		auto shape = make_shared<PlanePhysicsShape>(1, 1);
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({0, -5, 0});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}

	{ // sphere
		auto node = Node::NamedNode("Sphere physics shape node");
		auto shape = make_shared<SpherePhysicsShape>(1);
		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
		node->physicsBody(body);
		node->position({0, 0, 5});
		node->position({node->position().x, node->position().y+10, node->position().y});

		scene.rootNode()->addChild(node);
	}
}

//shared_ptr<CapsulePhysicsShape> ChainCapsule(float rotationRad) {
//
//}

//void SpawnChainMail(Scene& scene) {
//
//	static const float TORUS_MINOR_RADIUS = .9;
//	static const float TORUS_MAJOR_RADIUS = 1;
//
//	static bool once = false;
//	if (!once) {
//		once = true;
//
//		static const float TWO_PI = 2 * 3.14159265358;
//
//
////	scene.rootNode()->addChild(PhysicsChainElement(TORUS_MINOR_RADIUS,
////												   TORUS_MAJOR_RADIUS));
//
//		auto ringPhysicsNode = Node::NamedNode("Ring physics shape node");
//		//auto ringVisualNode =
//
//		static const float CAPSULE_RADIUS = .1;
////	static const float CAPSULE_HEIGHT = (TWO_PI * 1) / 8;
//		static const float TORUS_MID_RADIUS = TORUS_MAJOR_RADIUS - (TORUS_MAJOR_RADIUS - TORUS_MINOR_RADIUS);
//		static const float CAPSULE_HEIGHT = (TWO_PI * TORUS_MID_RADIUS) / 8.0;
////	static auto partShape = make_shared<CapsulePhysicsShape>(CAPSULE_RADIUS,
////															 CAPSULE_HEIGHT);
//		static auto visualGeo = make_shared<Capsule>(CAPSULE_RADIUS,
//													 CAPSULE_HEIGHT,
//													 16, 16, 16);
//
//		for (int s = 0; s < 8; ++s) {
//
//			float angle = (TWO_PI / 8.0) * (float) s;
//
//			auto partNode = Node::NamedNode("Ring capsule part node " + to_string(s + 1));
//			partNode->geometry(visualGeo);
//
//			quat rotation = angleAxis(angle, vec3(0, 0, 1));
//			mat4 rotMatrix = mat4_cast(rotation);
//			mat4 translation = translate(mat4(1.0f), vec3(1, 0, 0));
//			mat4 transform = rotMatrix * translation;
//			partNode->transform(transform);
//
//			partNode->hidden(true);
//
//			ringPhysicsNode->addChild(partNode);
//		}
//
//		auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, ringPhysicsNode);
//		auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
//		//body->affectedByGravity(false);
//		ringPhysicsNode->physicsBody(body);
//
//		ringPhysicsNode->position({0, 1, 0});
//
////	auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
////	body->affectedByGravity(false);
////	node->physicsBody(body);
////	node->position({0, 5, 0});
//
//		scene.rootNode()->addChild(ringPhysicsNode);
//	}
//	else {
//		auto ringPhysicsNode = scene.rootNode()->child("Ring physics shape node", true);
//
//		auto geometry = make_shared<Torus>(TORUS_MINOR_RADIUS+(TORUS_MINOR_RADIUS/32.0),
//										   TORUS_MAJOR_RADIUS+(TORUS_MAJOR_RADIUS/32.0), 128, 128);
//		auto ringVisualNode = Node::GeometryNode(geometry);
//
//		ringPhysicsNode->addChild(ringVisualNode);
//	}
//}

shared_ptr<Node> ChainmailLink(float minorRadius, float majorRadius) {

	static const float TWO_PI = 2 * 3.14159265358;

	static auto ringPhysicsNode = Node::NamedNode("Ring physics shape node");

	static const float CAPSULE_RADIUS = .1;
	static const float TORUS_MID_RADIUS = majorRadius - (majorRadius - minorRadius);
	static const float CAPSULE_HEIGHT = (TWO_PI * TORUS_MID_RADIUS) / 8.0;
	static const auto visualGeo = make_shared<Capsule>(CAPSULE_RADIUS,
													   CAPSULE_HEIGHT,
													   16, 16, 16);

	for (int s = 0; s < 8; ++s) {

		float angle = (float)(TWO_PI / 8.0) * (float)s;

		auto partNode = Node::NamedNode("Ring capsule part node " + to_string(s + 1));
		partNode->geometry(visualGeo);

		quat rotation = angleAxis(angle, vec3(0, 0, 1));
		mat4 rotMatrix = mat4_cast(rotation);
		mat4 translation = translate(mat4(1.0f), vec3(1, 0, 0));
		mat4 transform = rotMatrix * translation;
		partNode->transform(transform);

		//partNode->hidden(true);

		ringPhysicsNode->addChild(partNode);
	}

	static const auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, ringPhysicsNode.get());

	auto torusGeometry = make_shared<Torus>(minorRadius+(minorRadius/32.0),
											majorRadius+(majorRadius/32.0), 128, 128);
	auto ringVisualNode = Node::GeometryNode(torusGeometry);

	auto colorProperty = make_shared<MaterialProperty>(Color::LightGray());
	auto colorMaterial = make_shared<Material>(nullptr, colorProperty, nullptr);
	torusGeometry->addMaterial(colorMaterial);

	auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
	//body->affectedByGravity(false);
	ringVisualNode->physicsBody(body);

	ringVisualNode->position({0, 1, 0});

//	scene.rootNode()->addChild(ringVisualNode);
	return ringVisualNode;
}

void SpawnChainMail(Scene& scene) {

	static const float PI = 3.14159265358;

	static const float TORUS_MINOR_RADIUS = .9;
	static const float TORUS_MAJOR_RADIUS = 1;

	static const int CHAINMAIL_WIDTH = 3;
	static const int CHAINMAIL_HEIGHT = 4;

	static const int GROUND_OFFSET = 25;

//	for (int w=0; w<CHAINMAIL_WIDTH; ++w) {
//		for (int h=0; h<CHAINMAIL_HEIGHT; ++h) {
//			auto link = ChainmailLink(TORUS_MINOR_RADIUS, TORUS_MAJOR_RADIUS);
//			link->rotation({1, 0, 0}, (float) (w % 2 == 0 ? (PI / 6.0) : (-PI / 6.0)));
//			link->position({(3. * (2 * TORUS_MINOR_RADIUS) / 3.0) * w,
//							10 + (3. * (2 * TORUS_MINOR_RADIUS) / 3.0) * h,
//							0});
//			scene.rootNode()->addChild(link);
//		}
//	}

	auto chainmailNode = Node::NamedNode("chainmail");

	// horizontal chain
	for (int w=0; w<CHAINMAIL_WIDTH; ++w) {
		for (int h=0; h<CHAINMAIL_HEIGHT; ++h) {
			auto link = ChainmailLink(TORUS_MINOR_RADIUS, TORUS_MAJOR_RADIUS);
//		link->rotation({1, 0, 0}, (float) (w % 2 == 0 ? (PI / 6.0) : (-PI / 6.0)));
//			link->rotation({1, 0, 0}, PI / 6.0);
			float rotation = PI/12.0;
			float wStagger = 0;
			if (h%2 == 0) {
				rotation = -PI/12.0;
				wStagger = TORUS_MAJOR_RADIUS* 1.15;
			}
			link->rotation({1, 0, 0}, rotation);
			//link->rotation({1, 0, 0}, (float)(h%2 == 0 ? (PI/6.0) : (-PI/6.0)));
			//auto stagger = (w%2 == 0 ? 0 : TORUS_MAJOR_RADIUS);
			auto stagger = 0;
			link->position({( ( ((2 * TORUS_MAJOR_RADIUS) * 1.15) * w) + wStagger),
							/*GROUND_OFFSET*/0 + ((1 * TORUS_MAJOR_RADIUS) * 1.15) * h,
							0});
			chainmailNode->addChild(link);
			//scene.rootNode()->addChild(link);
		}
	}

	chainmailNode->rotation({1, 0, 0}, PI/2.0);
	chainmailNode->position({-chainmailNode->extent().x/2.0 + TORUS_MAJOR_RADIUS,
							 GROUND_OFFSET,
							 -chainmailNode->extent().y/2.0 + TORUS_MAJOR_RADIUS});
	scene.rootNode()->addChild(chainmailNode);

//	auto link = ChainmailLink(TORUS_MINOR_RADIUS, TORUS_MAJOR_RADIUS);
//	scene.rootNode()->addChild(link);

//	static const float TORUS_MINOR_RADIUS = .9;
//	static const float TORUS_MAJOR_RADIUS = 1;
//
//	static const float TWO_PI = 2 * 3.14159265358;
//
//	static auto ringPhysicsNode = Node::NamedNode("Ring physics shape node");
//
//	static const float CAPSULE_RADIUS = .1;
//	static const float TORUS_MID_RADIUS = TORUS_MAJOR_RADIUS - (TORUS_MAJOR_RADIUS - TORUS_MINOR_RADIUS);
//	static const float CAPSULE_HEIGHT = (TWO_PI * TORUS_MID_RADIUS) / 8.0;
//	static auto visualGeo = make_shared<Capsule>(CAPSULE_RADIUS,
//												 CAPSULE_HEIGHT,
//												 16, 16, 16);
//
//	for (int s = 0; s < 8; ++s) {
//
//		float angle = (TWO_PI / 8.0) * (float) s;
//
//		auto partNode = Node::NamedNode("Ring capsule part node " + to_string(s + 1));
//		partNode->geometry(visualGeo);
//
//		quat rotation = angleAxis(angle, vec3(0, 0, 1));
//		mat4 rotMatrix = mat4_cast(rotation);
//		mat4 translation = translate(mat4(1.0f), vec3(1, 0, 0));
//		mat4 transform = rotMatrix * translation;
//		partNode->transform(transform);
//
//		//partNode->hidden(true);
//
//		ringPhysicsNode->addChild(partNode);
//	}
//
//	auto shape = make_shared<PhysicsShape>(PHYSICS_SHAPE_TYPE::CONVEX_HULL, ringPhysicsNode);
//
//	auto torusGeometry = make_shared<Torus>(TORUS_MINOR_RADIUS+(TORUS_MINOR_RADIUS/32.0),
//											TORUS_MAJOR_RADIUS+(TORUS_MAJOR_RADIUS/32.0), 128, 128);
//	auto ringVisualNode = Node::GeometryNode(torusGeometry);
//
//	auto colorProperty = make_shared<MaterialProperty>(Color::LightGray());
//	auto colorMaterial = make_shared<Material>(nullptr, colorProperty, nullptr);
//	torusGeometry->addMaterial(colorMaterial);
//
//	auto body = make_shared<PhysicsBody>(PHYSICS_BODY_TYPE::DYNAMIC, shape);
//	//body->affectedByGravity(false);
//	ringVisualNode->physicsBody(body);
//
//	ringVisualNode->position({0, 1, 0});
//
//	scene.rootNode()->addChild(ringVisualNode);
}



//{
//// orientation indicator
//static auto shaftElement = make_shared<Cylinder>(.1, 1, 16, 16)->elements().front();
//static auto coneElement = make_shared<Cone>(.5, .25, 16, 16)->elements().front();
//
//auto redMaterialProperty = MaterialProperty::ColorProperty(Color::Red());
//auto xShaftGeometry = make_shared<Geometry>(shaftElement);
//
////	auto xArrowNode = Node::NamedNode("x arrow node");
////	xArrowNode->addChildren({Node::GeometryNode(shaftGeometry), Node::GeometryNode(coneGeometry)});
////	auto yArrowNode = Node::NamedNode("y arrow node");
////	yArrowNode->addChildren({Node::GeometryNode(shaftGeometry), Node::GeometryNode(coneGeometry)});
////	auto zArrowNode = Node::NamedNode("z arrow node");
////	zArrowNode->addChildren({Node::GeometryNode(shaftGeometry), Node::GeometryNode(coneGeometry)});
////	auto orientationNode = Node::NamedNode("Orientation indicator node");
////	orientationNode->addChildren({xArrowNode, yArrowNode, zArrowNode});
////	scene->rootNode()->addChild(orientationNode);
//}
