
if (UNIX AND APPLE)
	message("[MACOS]")
	set(MACOS TRUE)
	set(CMAKE_OSX_ARCHITECTURES "x86_64")
	add_definitions("-DAPPLE" "-DMACOS")
	if (CMAKE_GENERATOR STREQUAL "Xcode")
		set(XCODE TRUE)
		add_definitions("-DXCODE")
	endif()
endif()

if (UNIX AND NOT APPLE AND NOT ANDROID AND NOT MINGW)
	message("[LINUX]")
	set(LINUX TRUE)
	add_definitions("-DLINUX")
endif()

if (WIN32)
	message("[WIN32]")
	set(WINDOWS TRUE)
	set(WIN32 TRUE)
	add_definitions("-DWINDOWS" "-DBT_NO_SIMD_OPERATOR_OVERLOADS")
endif()

if (WIN64)
	message("[WIN64]")
	set(WINDOWS TRUE)
	set(WIN64 TRUE)
	add_definitions("-DWINDOWS")
endif()

if (ANDROID)
	message("[ANDROID]")
	set(ANDROID TRUE)
	add_definitions("-DANDROID")
endif()

if (RPI)
	message("[RPI]")
	set(RPI TRUE)
	add_definitions("-DRPI")
endif()

if (MACOS OR WINDOWS OR LINUX)
	message("[DESKTOP]")
	set(DESKTOP TRUE)
	add_definitions("-DDESKTOP")
endif()

if (ANDROID OR RPI)
	message("[OPENGL_ES]")
	set(OPENGL_ES TRUE)
	add_definitions("-DOPENGL_ES")
else ()
	message("[OPENGL_CORE]")
	set(OPENGL_CORE TRUE)
	add_definitions("-DOPENGL_CORE")
endif ()
